infix using "C:\COUNTRIES\NM61\NMMR61FL.dct"

label variable mcaseid  "Case Identification"
label variable mv000    "Country code and phase"
label variable mv001    "Cluster number"
label variable mv002    "Household number"
label variable mv003    "Respondent's line number"
label variable mv004    "Ultimate area unit"
label variable mv005    "Men's sample weight (6 decimals)"
label variable mv006    "Month of interview"
label variable mv007    "Year of interview"
label variable mv008    "Date of interview (CMC)"
label variable mv009    "Month of birth"
label variable mv010    "Year of birth"
label variable mv011    "Date of birth (CMC)"
label variable mv012    "Current age"
label variable mv013    "Age in 5-year groups"
label variable mv014    "Completeness of age information"
label variable mv015    "Result of interview"
label variable mv016    "Day of interview"
label variable mv021    "Primary sampling unit"
label variable mv022    "Sample stratum number"
label variable mv023    "Sample domain"
label variable mv024    "Region"
label variable mv025    "Type of place of residence"
label variable mv026    "NA - De facto place of residence"
label variable mv027    "Number of visits"
label variable mv028    "Interviewer identification"
label variable mv029    "Keyer identification"
label variable mv030    "Field supervisor"
label variable mv031    "Field editor"
label variable mv032    "Office editor"
label variable mv034_1  "Line number of wife/partner"
label variable mv034_2  "Line number of wife/partner"
label variable mv034_3  "Line number of wife/partner"
label variable mv034_4  "Line number of wife/partner"
label variable mv034_5  "Line number of wife/partner"
label variable mv034_6  "Line number of wife/partner"
label variable mv034_7  "Line number of wife/partner"
label variable mv034_8  "Line number of wife/partner"
label variable mv034a_1 "NA - Wife or partner***"
label variable mv034a_2 "NA - Wife or partner***"
label variable mv034a_3 "NA - Wife or partner***"
label variable mv034a_4 "NA - Wife or partner***"
label variable mv034a_5 "NA - Wife or partner***"
label variable mv034a_6 "NA - Wife or partner***"
label variable mv034a_7 "NA - Wife or partner***"
label variable mv034a_8 "NA - Wife or partner***"
label variable mv034b_1 "Age of wife/partner"
label variable mv034b_2 "Age of wife/partner"
label variable mv034b_3 "Age of wife/partner"
label variable mv034b_4 "Age of wife/partner"
label variable mv034b_5 "Age of wife/partner"
label variable mv034b_6 "Age of wife/partner"
label variable mv034b_7 "Age of wife/partner"
label variable mv034b_8 "Age of wife/partner"
label variable mv035    "Number of wives/partners"
label variable mv801    "Time interview started (hhmm - 24 hour clock)"
label variable mv802    "Time interview ended (hhmm - 24 hour clock)"
label variable mv803    "Length of interview in minutes"
label variable mv101    "Region"
label variable mv102    "Type of place of residence"
label variable mv103    "NA - Childhood place of residence***"
label variable mv104    "NA - Years lived in place of residence"
label variable mv105    "NA - Type of place of previous residence"
label variable mv106    "Educational level"
label variable mv107    "Highest year of education (at level in MV106)"
label variable mv130    "Religion"
label variable mv131    "NA - Ethnicity"
label variable mv133    "Total number of years of education"
label variable mv134    "NA - De facto place of residence"
label variable mv135    "Usual resident or visitor"
label variable mv136    "Number of household members (total listed)"
label variable mv138    "Number of eligible men in household (de facto)"
label variable mv149    "Educational attainment"
label variable mv150    "Relationship to household head"
label variable mv151    "Sex of household head"
label variable mv152    "Age of household head"
label variable mv155    "Literacy"
label variable mv156    "Ever participated in a literacy program (excluding primary school)"
label variable mv157    "Frequency of reading newspaper or magazine"
label variable mv158    "Frequency of listening to radio"
label variable mv159    "Frequency of watching television"
label variable mv167    "Times away from home in last 12 months"
label variable mv168    "Away for more than one month in last 12 months"
label variable mv190    "Wealth index"
label variable mv191    "Wealth index factor score (5 decimals)"
label variable mv201    "Total children ever born"
label variable mv202    "Sons at home"
label variable mv203    "Daughters at home"
label variable mv204    "Sons elsewhere"
label variable mv205    "Daughters elsewhere"
label variable mv206    "Sons who have died"
label variable mv207    "Daughters who have died"
label variable mv212    "Age of respondent at 1st birth"
label variable mv213    "Partner currently pregnant"
label variable mv217    "Knowledge of ovulatory cycle"
label variable mv218    "Number of living children"
label variable mv225    "NA - Most recent pregnancy wanted***"
label variable mv245    "Number of women fathered children with"
label variable mv246    "NA - Married to mother when first child was born***"
label variable mv247    "Age of most recent child"
label variable mv248    "Antenatal check-ups for the mother of most recent child"
label variable mv249    "Respondent present during check-ups for most recent child"
label variable mv250    "Place of birth of most recent child"
label variable mv251    "Reason for not delivering most recent child in health facility"
label variable mv252    "Amount a child should drink, when that child has diarrhea"
label variable mv301    "Knowledge of any contraceptive method"
label variable mv302    "NA - Ever use of any contraceptive method"
label variable m304a_01 "Type of contraceptive method"
label variable m304a_02 "Type of contraceptive method"
label variable m304a_03 "Type of contraceptive method"
label variable m304a_04 "Type of contraceptive method"
label variable m304a_05 "Type of contraceptive method"
label variable m304a_06 "Type of contraceptive method"
label variable m304a_07 "Type of contraceptive method"
label variable m304a_08 "Type of contraceptive method"
label variable m304a_09 "Type of contraceptive method"
label variable m304a_10 "Type of contraceptive method"
label variable m304a_11 "Type of contraceptive method"
label variable m304a_12 "Type of contraceptive method"
label variable m304a_13 "Type of contraceptive method"
label variable m304a_14 "Type of contraceptive method"
label variable m304a_15 "Type of contraceptive method"
label variable m304a_16 "Type of contraceptive method"
label variable m304a_17 "Type of contraceptive method"
label variable m304a_18 "Type of contraceptive method"
label variable m304a_19 "Type of contraceptive method"
label variable m304a_20 "Type of contraceptive method"
label variable mv304_01 "Knows contraceptive method"
label variable mv304_02 "Knows contraceptive method"
label variable mv304_03 "Knows contraceptive method"
label variable mv304_04 "Knows contraceptive method"
label variable mv304_05 "Knows contraceptive method"
label variable mv304_06 "Knows contraceptive method"
label variable mv304_07 "Knows contraceptive method"
label variable mv304_08 "Knows contraceptive method"
label variable mv304_09 "Knows contraceptive method"
label variable mv304_10 "Knows contraceptive method"
label variable mv304_11 "Knows contraceptive method"
label variable mv304_12 "Knows contraceptive method"
label variable mv304_13 "Knows contraceptive method"
label variable mv304_14 "Knows contraceptive method"
label variable mv304_15 "Knows contraceptive method"
label variable mv304_16 "Knows contraceptive method"
label variable mv304_17 "Knows contraceptive method"
label variable mv304_18 "Knows contraceptive method"
label variable mv304_19 "Knows contraceptive method"
label variable mv304_20 "Knows contraceptive method"
label variable mv305_01 "NA - Ever used contraceptive method"
label variable mv305_02 "NA - Ever used contraceptive method"
label variable mv305_03 "NA - Ever used contraceptive method"
label variable mv305_04 "NA - Ever used contraceptive method"
label variable mv305_05 "NA - Ever used contraceptive method"
label variable mv305_06 "NA - Ever used contraceptive method"
label variable mv305_07 "NA - Ever used contraceptive method"
label variable mv305_08 "NA - Ever used contraceptive method"
label variable mv305_09 "NA - Ever used contraceptive method"
label variable mv305_10 "NA - Ever used contraceptive method"
label variable mv305_11 "NA - Ever used contraceptive method"
label variable mv305_12 "NA - Ever used contraceptive method"
label variable mv305_13 "NA - Ever used contraceptive method"
label variable mv305_14 "NA - Ever used contraceptive method"
label variable mv305_15 "NA - Ever used contraceptive method"
label variable mv305_16 "NA - Ever used contraceptive method"
label variable mv305_17 "NA - Ever used contraceptive method"
label variable mv305_18 "NA - Ever used contraceptive method"
label variable mv305_19 "NA - Ever used contraceptive method"
label variable mv305_20 "NA - Ever used contraceptive method"
label variable mv307_01 "Contraceptive method currently used"
label variable mv307_02 "Contraceptive method currently used"
label variable mv307_03 "Contraceptive method currently used"
label variable mv307_04 "Contraceptive method currently used"
label variable mv307_05 "Contraceptive method currently used"
label variable mv307_06 "Contraceptive method currently used"
label variable mv307_07 "Contraceptive method currently used"
label variable mv307_08 "Contraceptive method currently used"
label variable mv307_09 "Contraceptive method currently used"
label variable mv307_10 "Contraceptive method currently used"
label variable mv307_11 "Contraceptive method currently used"
label variable mv307_12 "Contraceptive method currently used"
label variable mv307_13 "Contraceptive method currently used"
label variable mv307_14 "Contraceptive method currently used"
label variable mv307_15 "Contraceptive method currently used"
label variable mv307_16 "Contraceptive method currently used"
label variable mv307_17 "Contraceptive method currently used"
label variable mv307_18 "Contraceptive method currently used"
label variable mv307_19 "Contraceptive method currently used"
label variable mv307_20 "Contraceptive method currently used"
label variable mv312    "Current contraceptive method"
label variable mv313    "Current contraceptive by method type"
label variable mv323a   "Brand of condom used"
label variable mv325b   "NA - Cost of condoms (in CURRENCY) last time obtained"
label variable mv372a   "NA - Interviewer shown condom package"
label variable mv384a   "On radio heard about Family Planning in the last few months"
label variable mv384b   "On TV saw about Family Planning in the last few months"
label variable mv384c   "In newspaper read about Family Planning in the last few months"
label variable mv395    "Discussed Family Planning with health worker in last few months"
label variable mv396    "NA - Possible for a breastfeeding woman to get pregnant"
label variable mv3a09b  "NA - Number of condoms did get last time"
label variable mv3b17   "Source of condoms"
label variable mv3b25a  "Contraception is woman's business, man should not worry"
label variable mv3b25b  "Women who use contraception become promiscuous"
label variable mv463a   "Smokes cigarettes"
label variable mv463b   "Smokes pipe"
label variable mv463c   "Uses chewing tobacco"
label variable mv463d   "Uses snuff"
label variable mv463e   "Smokes Betel"
label variable mv463f   "Smokes Hubbly bubbly"
label variable mv463g   "Smokes Marijuana"
label variable mv463x   "Smokes other"
label variable mv463z   "Smokes nothing"
label variable mv464    "Number of cigarettes in last 24 hours"
label variable mv474    "Heard of tuberculosis or TB"
label variable mv474a   "Tuberculosis spread by: air through coughing or sneezing"
label variable mv474b   "Tuberculosis spread by: sharing utensils"
label variable mv474c   "Tuberculosis spread by: touching a person with TB"
label variable mv474d   "Tuberculosis spread by: food"
label variable mv474e   "Tuberculosis spread by: sexual contact"
label variable mv474f   "Tuberculosis spread by: mosquito bites"
label variable mv474g   "NA - Tuberculosis spread by: CS"
label variable mv474h   "NA - Tuberculosis spread by: CS"
label variable mv474i   "NA - Tuberculosis spread by: CS"
label variable mv474j   "NA - Tuberculosis spread by: CS"
label variable mv474x   "Tuberculosis spread by: other"
label variable mv474z   "Don't know how tuberculosis is spread"
label variable mv475    "Tuberculosis can be cured"
label variable mv476    "Would want tuberculosis infection in family to remain secret"
label variable mv477    "Number of injections in last 12 months"
label variable mv478    "Number of injections administered by a health worker"
label variable mv479    "NA - Place where given injection by health worker"
label variable mv480    "Syringe and needle from new, unopened package"
label variable mv481    "Covered by health insurance"
label variable mv481a   "NA - Health insurance type: mutual/community organization"
label variable mv481b   "Health insurance type: provided by employer"
label variable mv481c   "Health insurance type: social security"
label variable mv481d   "Health insurance type: private/commercially purchased"
label variable mv481e   "NA - Health insurance type: CS"
label variable mv481f   "NA - Health insurance type: CS"
label variable mv481g   "NA - Health insurance type: CS"
label variable mv481h   "NA - Health insurance type: CS"
label variable mv481x   "Health insurance type: other"
label variable mv482a   "NA - Arrange care of biological children under age 18***"
label variable mv482b   "NA - Primary caregiver of children under age 18***"
label variable mv482c   "NA - Arrange care of non-biological children < 18***"
label variable mv483    "Respondent circumcised"
label variable mv483a   "Age at circumcision"
label variable mv483b   "Who performed the circumcision"
label variable mv483c   "Place where circumcision was done"
label variable mv501    "Current marital status"
label variable mv502    "Currently/formerly/never in union"
label variable mv503    "Number of unions"
label variable mv504    "Currently residing with wife/partner"
label variable mv505    "Number of wives/partners"
label variable mv507    "Month of first cohabitation"
label variable mv508    "Year of first cohabitation"
label variable mv509    "Date of first cohabitation (CMC)"
label variable mv510    "Completeness of date information in MV509"
label variable mv511    "Age at first cohabitation"
label variable mv512    "Years since first cohabitation"
label variable mv513    "Cohabitation duration (grouped)"
label variable mv525    "Age at first sex"
label variable mv527    "Time since last sex"
label variable mv528    "Time since last sex (in days)"
label variable mv529    "Time since last sex (in months)"
label variable mv531    "Age at first sex (imputed)"
label variable mv532    "Flag for MV531"
label variable mv535    "Ever been married or in union"
label variable mv536    "Recent sexual activity"
label variable mv541    "NA - Intends to wait until marriage to have sex"
label variable mv602    "Fertility preference"
label variable mv603    "Preferred waiting time for birth of a/another child"
label variable mv604    "Preferred waiting time for birth of a/another child (grouped)"
label variable mv605    "Desire for more children"
label variable mv613    "Ideal number of children"
label variable mv614    "Ideal number of children (grouped)"
label variable mv616    "Desired time for future birth"
label variable mv621    "NA - Wife's desire for children***"
label variable mv627    "Ideal number of boys"
label variable mv628    "Ideal number of girls"
label variable mv629    "Ideal number of either sex"
label variable mv631    "NA - Problem if wife became pregnant***"
label variable mv633a   "NA - Wife justified refusing sex: husband has STI"
label variable mv633b   "Wife justified refusing sex: husband has other women"
label variable mv633c   "NA - Wife justified refusing sex: recent birth"
label variable mv633d   "NA - Wife justified refusing sex: tired, not in mood"
label variable mv633e   "NA - Wife justified refusing sex: CS reason"
label variable mv633f   "NA - Wife justified refusing sex: CS reason"
label variable mv633g   "NA - Wife justified refusing sex: CS reason"
label variable mv634a   "NA - Wife refuses to have sex, husband has right to: get angry"
label variable mv634b   "NA - Wife refuses to have sex, husband has right to: refuse financial support"
label variable mv634c   "NA - Wife refuses to have sex, husband has right to: use force for sex"
label variable mv634d   "NA - Wife refuses to have sex, husband has right to: have sex with another women"
label variable mv714    "Currently working"
label variable mv714a   "Have a job, but currently absent"
label variable mv716    "Occupation"
label variable mv717    "Occupation (grouped)"
label variable mv719    "NA - Works for family, others, self"
label variable mv721    "NA - Works at home or away"
label variable mv731    "Worked in last 12 months"
label variable mv732    "Employment all year/seasonal"
label variable mv739    "Person who usually decides how to spend respondent's earnings"
label variable mv740    "NA - Type of land where respondent works"
label variable mv741    "Type of earnings from respondent's work"
label variable mv743a   "Person who should have greater say: respondent's health care"
label variable mv743b   "Person who should have greater say: large household purchases"
label variable mv743c   "NA - Person who should have greater say: daily household purchases"
label variable mv743d   "NA - Person who should have greater say: visits to family or relatives"
label variable mv743e   "NA - Person who should have greater say: food to be cooked each day"
label variable mv743f   "NA - Person who should have greater say: deciding what to do with money wife ear"
label variable mv743g   "NA - Person who should have greater say: deciding how many children to have"
label variable mv744a   "Beating justified: wife goes out without telling husband"
label variable mv744b   "Beating justified: wife neglects the children"
label variable mv744c   "Beating justified: wife argues with husband"
label variable mv744d   "Beating justified: wife refuses to have sex with husband"
label variable mv744e   "Beating justified: wife burns food"
label variable mv745a   "Owns a house alone or jointly"
label variable mv745b   "Owns land alone or jointly"
label variable mv747a   "NA - Childbearing is a woman's concern"
label variable mv747b   "NA - Important for mother/child health to get assistance at delivery"
label variable mv750    "Ever heard of a Sexually Transmitted Infection (STI)"
label variable mv751    "Ever heard of AIDS"
label variable mv754bp  "NA - Reduce risk of getting HIV: do not have sex at all"
label variable mv754cp  "Reduce risk of getting HIV: always use condoms during sex"
label variable mv754dp  "Reduce risk of getting HIV: have 1 sex partner only, who has no other partners"
label variable mv754jp  "Can get HIV from mosquito bites"
label variable mv754wp  "Can get HIV by sharing food with person who has AIDS"
label variable mv756    "A healthy looking person can have HIV"
label variable mv761    "Condom used during last sex with most recent partner"
label variable mv761b   "Condom used during last sex with 2nd to most recent partner"
label variable mv761c   "Condom used during last sex with 3rd to most recent partner"
label variable mv762aa  "Source for condoms: government hospital"
label variable mv762ab  "Source for condoms: government health center"
label variable mv762ac  "Source for condoms: government primary health care clinic"
label variable mv762ad  "Source for condoms: outreach point"
label variable mv762ae  "Source for condoms: mobile clinic"
label variable mv762af  "Source for condoms: fieldworker / community health care provider"
label variable mv762ag  "Source for condoms: other public sector"
label variable mv762ah  "NA - Source for condoms: CS public"
label variable mv762ai  "NA - Source for condoms: CS public"
label variable mv762aj  "Source for condoms: private hospital"
label variable mv762ak  "Source for condoms: pharmacy"
label variable mv762al  "Source for condoms: private doctor"
label variable mv762am  "Source for condoms: private clinic"
label variable mv762an  "Source for condoms: other private medical sector"
label variable mv762ao  "NA - Source for condoms: CS private"
label variable mv762ap  "NA - Source for condoms: CS private"
label variable mv762aq  "NA - Source for condoms: CS private"
label variable mv762ar  "NA - Source for condoms: CS private"
label variable mv762as  "Source for condoms: shop"
label variable mv762at  "Source for condoms: church"
label variable mv762au  "Source for condoms: friend/relative"
label variable mv762av  "Source for condoms: school"
label variable mv762aw  "NA - Source for condoms: CS other"
label variable mv762ax  "Source for condoms: other"
label variable mv762az  "Don't know any source for condoms"
label variable mv762ba  "Source for female condoms: government hospital"
label variable mv762bb  "Source for female condoms: government health center"
label variable mv762bc  "Source for female condoms: government primary health care clnic"
label variable mv762bd  "Source for female condoms: outreach point"
label variable mv762be  "Source for female condoms: mobile clinic"
label variable mv762bf  "Source for female condoms: fieldworker/ community health care provider"
label variable mv762bg  "Source for female condoms: other public sector"
label variable mv762bh  "NA - Source for female condoms: CS public"
label variable mv762bi  "NA - Source for female condoms: CS public"
label variable mv762bj  "Source for female condoms: private hospital/clinic"
label variable mv762bk  "Source for female condoms: pharmacy"
label variable mv762bl  "Source for female condoms: private doctor"
label variable mv762bm  "Source for female condoms: private clinic"
label variable mv762bn  "Source for female condoms: other private medical section"
label variable mv762bo  "NA - Source for female condoms: CS private"
label variable mv762bp  "NA - Source for female condoms: CS private"
label variable mv762bq  "NA - Source for female condoms: CS private"
label variable mv762br  "NA - Source for female condoms: CS private"
label variable mv762bs  "Source for female condoms: shop"
label variable mv762bt  "Source for female condoms: church"
label variable mv762bu  "Source for female condoms: friend/relative"
label variable mv762bv  "Source for female condoms: school"
label variable mv762bw  "NA - Source for female condoms: CS other"
label variable mv762bx  "Source for female condoms: other"
label variable mv762bz  "Don't know any source for female condoms"
label variable mv763a   "Had any STI in last 12 months"
label variable mv763b   "Had genital sore/ulcer in last 12 months"
label variable mv763c   "Had genital discharge in last 12 months"
label variable mv763d   "NA - Had CS STI in last 12 months"
label variable mv763e   "NA - Had CS STI in last 12 months"
label variable mv763f   "NA - Had CS STI in last 12 months"
label variable mv763g   "NA - Had CS STI in last 12 months"
label variable mv766a   "Number of sex partners, excluding spouse, in last 12 months"
label variable mv766b   "Number of sex partners, including spouse, in last 12 months"
label variable mv767a   "Relationship with most recent sex partner"
label variable mv767b   "Relationship with 2nd to most recent sex partner"
label variable mv767c   "Relationship with 3rd to most recent sex partner"
label variable mv768a   "NA - Length of time had sex relations with most recent partner"
label variable mv768b   "NA - Length of time had sex relations with 2nd to most recent partner"
label variable mv768c   "NA - Length of time had sex relations with 3rd to most recent partner"
label variable mv769    "Can get a condom"
label variable mv769a   "Can get a female condom"
label variable mv770    "Sought advice/treatment for last STI infection"
label variable mv770a   "Sought STI advice/treatment from: government hospital"
label variable mv770b   "Sought STI advice/treatment from: government health center"
label variable mv770c   "Sought STI advice/treatment from: stand-alone VCT center"
label variable mv770d   "Sought STI advice/treatment from: government primary health care clinic"
label variable mv770e   "Sought STI advice/treatment from: outreach point"
label variable mv770f   "Sought STI advice/treatment from: mobile clinic"
label variable mv770g   "Sought STI advice/treatment from: school based clinic"
label variable mv770h   "Sought STI advice/treatment from: other public sector"
label variable mv770i   "NA - Sought STI advice/treatment from: CS public"
label variable mv770j   "NA - Sought STI advice/treatment from: CS public"
label variable mv770k   "Sought STI advice/treatment from: private hospital/clinic/doctor"
label variable mv770l   "Sought STI advice/treatment from: stand-alone VCT center"
label variable mv770m   "Sought STI advice/treatment from: pharmacy"
label variable mv770n   "Sought STI advice/treatment from: mobile clinic"
label variable mv770o   "Sought STI advice/treatment from: filedworker"
label variable mv770p   "Sought STI advice/treatment from: school based clinic"
label variable mv770q   "Sought STI advice/treatment from: other private sector"
label variable mv770r   "NA - Sought STI advice/treatment from: CS private"
label variable mv770s   "NA - Sought STI advice/treatment from: CS private"
label variable mv770t   "Sought STI advice/treatment from: Shop"
label variable mv770u   "NA - Sought STI advice/treatment from: CS other"
label variable mv770v   "NA - Sought STI advice/treatment from: CS other"
label variable mv770w   "NA - Sought STI advice/treatment from: CS other"
label variable mv770x   "Sought STI advice/treatment from: other"
label variable mv774a   "HIV transmitted during pregnancy"
label variable mv774b   "HIV transmitted during delivery"
label variable mv774c   "HIV transmitted by breastfeeding"
label variable mv775    "NA - Knows someone who has, or is suspected of having, HIV"
label variable mv777    "Would want HIV infection in family to remain secret"
label variable mv778    "Willing to care for relative with AIDS"
label variable mv779    "A female teacher infected with HIV, but is not sick, should be allowed to contin"
label variable mv780    "Children should be taught about condoms to avoid AIDS"
label variable mv781    "Ever been tested for HIV"
label variable mv783    "Know a place to get HIV test"
label variable mv784a   "Place for HIV test: government hospital"
label variable mv784b   "Place for HIV test: government health center"
label variable mv784c   "Place for HIV test: stand-alone VCT center"
label variable mv784d   "Place for HIV test: government primary health care clinic"
label variable mv784e   "Place for HIV test: outreach point"
label variable mv784f   "Place for HIV test: mobile clinic"
label variable mv784g   "Place for HIV test: school based clinic"
label variable mv784h   "Place for HIV test: other public sector"
label variable mv784i   "NA - Place for HIV test: CS public"
label variable mv784j   "NA - Place for HIV test: CS public"
label variable mv784k   "Place for HIV test: private hospital/clinic/doctor"
label variable mv784l   "Place for HIV test: stand-alone VCT center"
label variable mv784m   "Place for HIV test: pharmacy"
label variable mv784n   "Place for HIV test: mobile clinic"
label variable mv784o   "Place for HIV test: fieldworker"
label variable mv784p   "Place for HIV test: school based clinic"
label variable mv784q   "Place for HIV test: other private sector"
label variable mv784r   "NA - Place for HIV test: CS private"
label variable mv784s   "Place for HIV test: home"
label variable mv784t   "Place for HIV test: correctional facility"
label variable mv784u   "NA - Place for HIV test: CS other"
label variable mv784v   "NA - Place for HIV test: CS other"
label variable mv784x   "Place for HIV test: other"
label variable mv785    "Heard about other STIs"
label variable mv791    "Have ever paid anyone in exchange for sex"
label variable mv793    "Paid for sex in last 12 months"
label variable mv793a   "Condom used last time paid for sex in last 12 months"
label variable mv793b   "Condom used every time paid for sex in last 12 months"
label variable mv820    "NA - Condom used at first sex"
label variable mv822    "Wife justified asking husband to use condom if he has STI"
label variable mv823    "Can get HIV by witchcraft or supernatural means"
label variable mv824    "Drugs to avoid HIV transmission to baby during pregnancy"
label variable mv825    "Would buy vegetables from vendor with HIV"
label variable mv826    "NA - Last time tested for HIV"
label variable mv826a   "Months ago most recent HIV test"
label variable mv827    "NA - Last HIV test: on your own, offered or required"
label variable mv828    "Received result from last HIV test"
label variable mv829    "Place where last HIV test was taken"
label variable mv832b   "Time since last sex with 2nd to most recent partner"
label variable mv832c   "Time since last sex with 3rd to most recent partner"
label variable mv833a   "Used condom every time had sex with most recent partner in last 12 months"
label variable mv833b   "Used condom every time had sex with 2nd to most recent partner in last 12 months"
label variable mv833c   "Used condom every time had sex with 3rd to most recent partner in last 12 months"
label variable mv834a   "Age of most recent partner"
label variable mv834b   "Age of 2nd to most recent partner"
label variable mv834c   "Age of 3rd to most recent partner"
label variable mv835a   "NA - Alcohol consumption at last sex with most recent partner"
label variable mv835b   "NA - Alcohol consumption at last sex with 2nd to most recent partner"
label variable mv835c   "NA - Alcohol consumption at last sex with 3rd to most recent partner"
label variable mv836    "Total lifetime number of sex partners"
label variable mv837    "NA - Heard of drugs to help HIV infected people live longer"
label variable mv844    "NA - Knows someone denied health services for having, or suspected of having, HI"
label variable mv845    "NA - Knows someone denied social event for having, or suspected of having, HIV; "
label variable mv846    "NA - Knows someone verbally abused for having, or suspected of having, HIV; in l"
label variable mv847    "NA - People with HIV should be ashamed of themselves"
label variable mv848    "NA - People with HIV should be blamed for bringing disease to community"
label variable mv849    "NA - Children 12-14 should be taught to wait for sex until marriage"
label variable mv851a   "NA - Young men should wait for sex until marriage"
label variable mv851b   "NA - Most young men wait for sex until marriage"
label variable mv851c   "NA - Unmarried sexually active men should have only one partner"
label variable mv851d   "NA - Most unmarried sexually active men have only one partner"
label variable mv851e   "NA - Married men should only have sex with their wives"
label variable mv851f   "NA - Most married men only have sex with their wives"
label variable mv851g   "NA - Young women should wait for sex until marriage"
label variable mv851h   "NA - Most young women wait for sex until marriage"
label variable mv851i   "NA - Unmarried sexually active women should have only one partner"
label variable mv851j   "NA - Most unmarried sexually active women have only one partner"
label variable mv851k   "NA - Married women should only have sex with their husbands"
label variable mv851l   "NA - Most married women only have sex with their husbands"
label variable mv852a   "How long ago first had sex with most recent partner"
label variable mv852b   "How long ago first had sex with 2nd most recent partner"
label variable mv852c   "How long ago first had sex with 3rd most recent partner"
label variable mv853a   "Times in last 12 months had sex with most recent partner"
label variable mv853b   "Times in last 12 months had sex with 2nd most recent partner"
label variable mv853c   "Times in last 12 months had sex with 3rd most recent partner"
label variable mv854a   "Concurrent sexual partners"
label variable mv854b   "Cumulative concurrent sexual partners"
label variable sm114    "Main language spoken in home"
label variable sm218a   "Tested for HIV at ANC checkups when wife was pregnant with youngest son"
label variable sm614f   "Beating justified: friendly with other men"
label variable sm714a   "Willingness to share the HIV results"
label variable sm714b   "HIV test results"
label variable sm714c   "Received counselling before and after testing"
label variable sm714d   "Disclosure of results to partner"
label variable sm715a   "Received HIV counselling and testing individually or as a couple"
label variable sm715b   "Consideration for HIV counselling and testing as couple in future"
label variable sm715c   "Main reason for not considering HIV counselling and testing as a couple in futur"
label variable sm715e   "Currently taking ARV's"
label variable sm715f   "Main reason for not taking ARV's daily"
label variable sm804a   "If had baby boy, would he be circumcised"
label variable sm804b   "Any benefits to Male circumcision"
label variable sm804ca  "Benefits of male circumcision: recommended by tradition/religion"
label variable sm804cb  "Benefits of male circumcision: good for health/hygiene"
label variable sm804cc  "Benefits of male circumcision: protects against getting HIV"
label variable sm804cd  "Benefits of male circumcision: protects against getting STDs"
label variable sm804ce  "Benefits of male circumcision: increase sexual satisfaction"
label variable sm804cf  "Benefits of male circumcision: easier to put on condom"
label variable sm804cx  "Benefits of male circumcision: other"
label variable sm804cy  "Benefits of male circumcision: don't know any benefit"
label variable sm804fa  "Tuberculosis symptoms: persistent cough ( more than 2 weeks)"
label variable sm804fb  "Tuberculosis symptoms: weight loss"
label variable sm804fc  "Tuberculosis symptoms: poor appetite"
label variable sm804fd  "Tuberculosis symptoms: night sweating"
label variable sm804fe  "Tuberculosis symptoms: chest pain"
label variable sm804ff  "Tuberculosis symptoms: fever"
label variable sm804fx  "Tuberculosis symptoms: other"
label variable sm804fz  "Tuberculosis symptoms: don't know"
label variable sm811a   "Use or smoke tobacco products daily"
label variable sm811b   "Age when first started using tobacco products daily"
label variable sm811c   "Ever consumption of alcohol"
label variable sm811f   "Consumption of alcohol during past 2 weeks"
label variable sm811g   "On average, Number of days had at least one alcoholic drink during past two week"
label variable sm811h   "On average, number of alcoholic drinks had per day during past two weeks"
label variable sm813a   "Exercises involved in causing high heart rate for at least 10 minutes"
label variable sm813b   "Number of days exercised for at least 10 minutes during last 7 days"
label variable sm813e   "Number of glasses of water drank on average in a day"
label variable sm813f   "Number of days eat fruits in a week"
label variable sm813g   "On average, number of time eat fruits in a day"
label variable sm813h   "Number of days eat vegetables in a week"
label variable sm813i   "On average, number of times you eat vegetables in day"
label variable sm813m   "Usage of seatbelt when seated in a vehicle in past 30 days"
label variable sm813o   "Heard of prostate cancer"
label variable sm813p   "Ever tested/examined for prostate cancer"
label variable sm813q   "Times you see or hear things not actually there"
label variable sm813r   "Felt seriously worthless/hopeless in past 12 months"
label variable sm813s   "Felt little interest/pleasure in past 2 weeks"
label variable sm813sn  "Number of days felt little interest/pleasure in past 2 weeks"
label variable sm813t   "Felt low energy/bad mood/sad in past 2 weeks"
label variable sm813tn  "Number of days felt low energy/bad mood/sad in past 2 weeks"
label variable sm813v   "Seek any medical care"
label variable mv044    "Selected for Domestic Violence module"
label variable dm005    "Weight for Domestic Violence (6 decimals)"
label variable dm101a   "Wife/partner jealous if respondent talks with other men"
label variable dm101b   "Wife/partner accuses respondent of unfaithfulness"
label variable dm101c   "Wife/partner does not permit respondent to meet female friends"
label variable dm101d   "Wife/partner tries to limit respondent's contact with family"
label variable dm101e   "Wife/partner insists on knowing where respondent is"
label variable dm101f   "Wife/partner doesn't trust respondent with money"
label variable dm102    "Number of control issues answered 'Yes'  (DM101 A-F = 1)"
label variable dm103a   "Ever been humiliated by wife/partner"
label variable dm103b   "Ever been threatened with harm by wife/partner"
label variable dm103c   "Ever been insulted or made to feel bad by wife/partner"
label variable dm104    "Experienced any emotional violence (DM103A-C series)"
label variable dm105a   "Ever been pushed, shook or had something thrown by wife/partner"
label variable dm105b   "Ever been slapped by wife/partner"
label variable dm105c   "Ever been punched with fist or hit by something harmful by wife/partner"
label variable dm105d   "Ever been kicked or dragged by wife/partner"
label variable dm105e   "Ever been strangled or burnt by wife/partner"
label variable dm105f   "Ever been threatened with knife/gun or other weapon by wife/partner"
label variable dm105h   "Ever been physically forced into unwanted sex by wife/partner"
label variable dm105i   "Ever been forced into other unwanted sexual acts by wife/partner"
label variable dm105j   "Ever had arm twisted or hair pulled by wife/partner"
label variable dm105k   "Ever been physically forced to perform sexual acts respondent didn't want to"
label variable dm106    "Experienced any less severe violence (DM105A-C,J) by wife/partner"
label variable dm107    "Experienced any severe violence (DM105D-F) by wife/partner"
label variable dm108    "Experienced any sexual violence (DM105H-I,K) by wife/partner"
label variable dm109    "Timing of first event (from DM105 series) in years after marriage"
label variable dm110a   "Ever had bruises because of wife/partner's actions"
label variable dm110b   "Ever had eye injuries, sprains, dislocations or burns because of wife/partner's "
label variable dm110d   "Ever had wounds, broken bones, broken teeth or other serious injury because of w"
label variable dm111    "Experienced any of listed wife/partner's actions (DM110x series)***"
label variable dm112    "Respondent ever physically hurt wife/partner when he was not hurting her"
label variable dm112a   "Frequency of physically hurting wife/partner in last 12 months"
label variable dm113    "Wife/partner drinks alcohol"
label variable dm114    "Frequency of wife/partner being drunk"
label variable dm115b   "Mother: Person who has ever physically hurt respondent"
label variable dm115c   "Father: Person who has ever physically hurt respondent"
label variable dm115d   "Daughter: Person who has ever physically hurt respondent"
label variable dm115f   "Sister/brother: Person who has ever physically hurt respondent"
label variable dm115g   "Other relative: Person who has ever physically hurt respondent"
label variable dm115k   "Current girlfriend: Person who has ever physically hurt respondent"
label variable dm115l   "Former girlfriend: Person who has ever physically hurt respondent"
label variable dm115o   "Mother-in-law: Person who has ever physically hurt respondent"
label variable dm115p   "Father-in-law: Person who has ever physically hurt respondent"
label variable dm115q   "Other in-law: Person who has ever physically hurt respondent"
label variable dm115v   "Teacher: Person who has ever physically hurt respondent"
label variable dm115w   "Employer: Person who has ever physically hurt respondent"
label variable dm115x   "Other: Person who has ever physically hurt respondent"
label variable dm115y   "No person other than husband/partner ever physically hurt respondent"
label variable dm115xe  "Police: Person who has ever physically hurt respondent"
label variable dm117a   "Frequency of being hit in last 12 months by other than husband/partner"
label variable dm119h   "Own family: Person respondent went to seek help"
label variable dm119i   "Wife/partner family: Person respondent went to seek help"
label variable dm119j   "Current/former wife/partner: Person respondent went to seek help"
label variable dm119k   "Current/former girlfriend: Person respondent went to seek help"
label variable dm119u   "Neighbor: Person respondent went to seek help"
label variable dm119x   "Other: Person respondent went to seek help"
label variable dm119xb  "Social service organization: Person respondent went to seek help"
label variable dm119xd  "Friend: Person respondent went to seek help"
label variable dm119xe  "Police: Person respondent went to seek help"
label variable dm119xf  "Religious leader: Person respondent went to seek help"
label variable dm119xg  "Lawyer: Person respondent went to seek help"
label variable dm119xh  "Doctor: Person respondent went to seek help"
label variable dm119y   "Respondent did not seek help from anyone"
label variable dm121    "Respondent's father ever beat her mother"
label variable dm122a   "Interview interrupted: husband's presence"
label variable dm122b   "Interview interrupted: other adult male's presence"
label variable dm122c   "Interview interrupted: adult female's presence"
label variable dm124    "Ever forced to have sex by anyone other than husband/partner in last 12 months"
label variable dm125    "Ever forced to perform unwanted sexual acts"
label variable dm126    "Age at first forced sexual act"
label variable dm127    "Person who forced respondent into first sexual act"
label variable dm128    "Ever told anyone else about violence"
label variable dm129    "Respondent afraid of wife/partner most of the time, sometimes or never"
label variable dm130a   "Previous wife/partner: ever hit, slap, kick or physically hurt respondent"
label variable dm130b   "Previous wife/partner: physically forced to have sex or to perform sexual acts"
label variable smlangua "Language of questionnaire"
label variable smlangresp "Language of respondent"
label variable smlangint "Language of interview"
label variable smtransl "Translator used"

#delimit ;
label define MV013   
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
     8 "50-54"
     9 "55-59"
    10 "60-64"
;
label define MV014   
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define MV015   
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define MV022   
     1 "Caprivi,urban"
     2 "Erongo, urban"
     3 "Hardap, urban"
     4 "Karas, urban"
     5 "Kavango, urban"
     6 "Khomas, urban"
     7 "Kunene, urban"
     8 "Ohangwena, urban"
     9 "Omaheke, urban"
    10 "Omusati, urban"
    11 "Oshana, urban"
    12 "Oshikoto, urban"
    13 "Otjozondjupa, urban"
    14 "Caprivi, rural"
    15 "Erongo, rural"
    16 "Hardap, rural"
    17 "Karas, rural"
    18 "Kavango, rural"
    19 "Khomas, rural"
    20 "Kunene, rural"
    21 "Ohangwena, rural"
    22 "Omaheke, rural"
    23 "Omusati, rural"
    24 "Oshana, rural"
    25 "Oshikoto, rural"
    26 "Otjozondjupa, rural"
;
label define MV023   
     1 "Caprivi,urban"
     2 "Erongo, urban"
     3 "Hardap, urban"
     4 "Karas, urban"
     5 "Kavango, urban"
     6 "Khomas, urban"
     7 "Kunene, urban"
     8 "Ohangwena, urban"
     9 "Omaheke, urban"
    10 "Omusati, urban"
    11 "Oshana, urban"
    12 "Oshikoto, urban"
    13 "Otjozondjupa, urban"
    14 "Caprivi, rural"
    15 "Erongo, rural"
    16 "Hardap, rural"
    17 "Karas, rural"
    18 "Kavango, rural"
    19 "Khomas, rural"
    20 "Kunene, rural"
    21 "Ohangwena, rural"
    22 "Omaheke, rural"
    23 "Omusati, rural"
    24 "Oshana, rural"
    25 "Oshikoto, rural"
    26 "Otjozondjupa, rural"
;
label define MV024   
     1 "Caprivi"
     2 "Erongo"
     3 "Hardap"
     4 "Karas"
     5 "Kavango"
     6 "Khomas"
     7 "Kunene"
     8 "Ohangwena"
     9 "Omaheke"
    10 "Omusati"
    11 "Oshana"
    12 "Oshikoto"
    13 "Otjozondjupa"
;
label define MV025   
     1 "Urban"
     2 "Rural"
;
label define MV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define MV027   
     9 "Missing"
;
label define MV028   
   999 "Missing"
;
label define MV029   
    99 "Missing"
;
label define MV030   
   999 "Missing"
;
label define MV031   
   999 "Missing"
;
label define MV032   
    99 "Missing"
;
label define MV034   
     0 "Wife not in household"
;
label define MV034A  
     1 "Wife"
     2 "Partner"
;
label define MV034B  
    99 "Missing"
;
label define MV035   
     0 "No wives/partners"
;
label define MV801   
  9999 "Missing"
;
label define MV802   
  9999 "Missing"
;
label define MV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define MV101   
     1 "Caprivi"
     2 "Erongo"
     3 "Hardap"
     4 "Karas"
     5 "Kavango"
     6 "Khomas"
     7 "Kunene"
     8 "Ohangwena"
     9 "Omaheke"
    10 "Omusati"
    11 "Oshana"
    12 "Oshikoto"
    13 "Otjozondjupa"
;
label define MV102   
     1 "Urban"
     2 "Rural"
;
label define MV103   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define MV104   
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV105   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define MV106   
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define MV107   
     0 "No years completed at level MV106"
;
label define MV130   
     1 "Roman catholic"
     2 "Protestant/Anglican"
     3 "Elcin"
     4 "Seventh-day adventist"
     5 "No religion"
    96 "Other"
;
label define MV131   
   999 "Missing"
;
label define MV133   
    97 "Inconsistent"
;
label define MV134   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define MV135   
     1 "Usual resident"
     2 "Visitor"
;
label define MV149   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define MV150   
     1 "Head"
     2 "Husband"
     3 "Son"
     4 "Son-in-law"
     5 "Grandson"
     6 "Father"
     7 "Father-in-law"
     8 "Brother"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "Don't know"
;
label define MV151   
     1 "Male"
     2 "Female"
;
label define MV152   
    97 "97+"
    98 "Don't know"
;
label define MV155   
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define MV156   
     0 "No"
     1 "Yes"
;
label define MV157   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV158   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV159   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV167   
     0 "None"
    90 "90+"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV168   
     0 "No"
     1 "Yes"
;
label define MV190   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define MV212   
    99 "Missing"
;
label define MV213   
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV217   
     1 "During her period"
     2 "After period ended"
     3 "Middle of the cycle"
     4 "Before period begins"
     5 "At any time"
     6 "Other"
     8 "Don't know"
;
label define MV225   
     1 "Then"
     2 "Later"
     3 "Not at all"
;
label define MV245   
    99 "Missing"
;
label define MV246   
     0 "No"
     1 "Yes"
;
label define MV247   
    99 "Missing"
;
label define MV248   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV249   
     0 "Not present"
     1 "Present"
;
label define MV250   
     1 "Hospital, health facility"
     2 "Other"
;
label define MV251   
     1 "Cost too much"
     2 "Facility closed"
     3 "Too far/no transportation"
     4 "Don't trust facility/poor quality service"
     5 "No female provider"
     6 "Not the first child"
     7 "Mother did not think it necessary"
     8 "Respondent did not think it necessary"
     9 "Family did not think it necessary"
    96 "Other"
    98 "Don't know"
;
label define MV252   
     0 "Nothing to drink"
     2 "Less than usual/much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define MV301   
     0 "Knows no method"
     1 "Knows only folkloric method"
     2 "Knows only traditional method"
     3 "Knows modern method"
;
label define MV302   
     0 "Never used"
     1 "Used only folkloric method"
     2 "Used only traditional method"
     3 "Used modern method"
;
label define M304A   
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define MV304   
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV305   
     0 "No"
     1 "Yes"
;
label define MV307   
     0 "No"
     1 "Yes"
;
label define MV312   
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Implants/Norplant"
    12 "Abstinence"
    13 "Lactational amenorrhea (LAM)"
    14 "Female condom"
    15 "Foam or jelly"
    17 "Other modern method"
    18 "Contraceptive patch"
    19 "Survey Specific method 3"
    20 "Survey Specific method 4"
    98 "Don't know"
;
label define MV313   
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
     8 "Don't know"
;
label define MV323A  
     1 "Smile"
     2 "Cool rider"
     3 "Sense"
     4 "Femidom"
    96 "Other"
    98 "Don't know"
;
label define MV325B  
9999995 "Free"
9999998 "Don't know"
;
label define MV372A  
     0 "Package not seen"
     1 "Package seen"
;
label define MV384A  
     0 "No"
     1 "Yes"
;
label define MV384B  
     0 "No"
     1 "Yes"
;
label define MV384C  
     0 "No"
     1 "Yes"
;
label define MV395   
     0 "No"
     1 "Yes"
     2 "Depends"
     8 "Don't know"
;
label define MV396   
     0 "No"
     1 "Yes"
     2 "Depends"
     8 "Don't know"
;
label define MV3A09B 
   998 "Don't know"
;
label define MV3B17  
    11 "Government hospital"
    12 "Government health center"
    13 "Government priimary health care clinic"
    14 "Outreach point"
    15 "Field worker/Community health care provider"
    16 "Other public"
    21 "Private hospital"
    22 "Private clinic"
    23 "Private pharmacy"
    24 "Private doctor"
    26 "Other private medical"
    31 "Shop"
    32 "Church"
    33 "Friends/relatives"
    34 "School"
    96 "Other"
;
label define MV3B25A 
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV3B25B 
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV463A  
     0 "No"
     1 "Yes"
;
label define MV463B  
     0 "No"
     1 "Yes"
;
label define MV463C  
     0 "No"
     1 "Yes"
;
label define MV463D  
     0 "No"
     1 "Yes"
;
label define MV463E  
     0 "No"
     1 "Yes"
;
label define MV463F  
     0 "No"
     1 "Yes"
;
label define MV463G  
     0 "No"
     1 "Yes"
;
label define MV463X  
     0 "No"
     1 "Yes"
;
label define MV463Z  
     0 "No"
     1 "Yes, smokes nothing"
;
label define MV464   
    98 "DK"
;
label define MV474   
     0 "No"
     1 "Yes"
;
label define MV474A  
     0 "No"
     1 "Yes"
;
label define MV474B  
     0 "No"
     1 "Yes"
;
label define MV474C  
     0 "No"
     1 "Yes"
;
label define MV474D  
     0 "No"
     1 "Yes"
;
label define MV474E  
     0 "No"
     1 "Yes"
;
label define MV474F  
     0 "No"
     1 "Yes"
;
label define MV474G  
     0 "No"
     1 "Yes"
;
label define MV474H  
     0 "No"
     1 "Yes"
;
label define MV474I  
     0 "No"
     1 "Yes"
;
label define MV474J  
     0 "No"
     1 "Yes"
;
label define MV474X  
     0 "No"
     1 "Yes"
;
label define MV474Z  
     0 "No"
     1 "Yes"
;
label define MV475   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV476   
     0 "No"
     1 "Yes, remain a secret"
     8 "Don't know/not sure/depends"
;
label define MV477   
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define MV478   
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define MV479   
    10 "PUBLIC SECTOR"
    20 "PRIVATE SECTOR"
    30 "OTHER"
    96 "Other"
;
label define MV480   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV481   
     0 "No"
     1 "Yes"
;
label define MV481A  
     0 "No"
     1 "Yes"
;
label define MV481B  
     0 "No"
     1 "Yes"
;
label define MV481C  
     0 "No"
     1 "Yes"
;
label define MV481D  
     0 "No"
     1 "Yes"
;
label define MV481E  
     0 "No"
     1 "Yes"
;
label define MV481F  
     0 "No"
     1 "Yes"
;
label define MV481G  
     0 "No"
     1 "Yes"
;
label define MV481H  
     0 "No"
     1 "Yes"
;
label define MV481X  
     0 "No"
     1 "Yes"
;
label define MV482A  
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV482B  
     0 "No"
     1 "Yes"
;
label define MV482C  
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV483   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV483A  
    95 "During childhood <5 years"
    98 "Don't know"
;
label define MV483B  
     1 "Traditional practitioner / family friend"
     2 "Health worker / professional"
    96 "Other"
    98 "Don't know"
;
label define MV483C  
     1 "Health facility"
     2 "Home of a health worker / professional"
     3 "Circumcision done at home"
     4 "Ritual site"
    96 "Other home / place"
    98 "Don't know"
;
label define MV501   
     0 "Never in union"
     1 "Married"
     2 "Living with partner"
     3 "Widowed"
     4 "Divorced"
     5 "No longer living together/separated"
;
label define MV502   
     0 "Never in union"
     1 "Currently in union/living with a woman"
     2 "Formerly in union/living with a woman"
;
label define MV503   
     1 "Once"
     2 "More than once"
;
label define MV504   
     1 "Living with him"
     2 "Staying elsewhere"
;
label define MV505   
    99 "Missing"
;
label define MV510   
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define MV513   
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
;
label define MV525   
     0 "Not had sex"
    96 "At first union"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV527   
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV528   
    31 "31+ days"
    95 "Within last 4 weeks"
    96 "Before last birth"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV529   
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV531   
     0 "Not had sex"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV532   
     0 "No flag"
     1 "After interview"
     2 "After conception >= 1 year"
     3 "After conception < 1 year"
     4 "At marriage, but never married"
     5 "At marriage, but after conception"
     6 "After marriage"
;
label define MV535   
     0 "No"
     1 "Formerly married"
     2 "Formerly lived with a woman"
     3 "Both, formerly married and lived with a woman"
;
label define MV536   
     0 "Never had sex"
     1 "Active in last 4 weeks"
     3 "Not active in last 4 weeks"
;
label define MV541   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV602   
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized (respondent or partner(s))"
     5 "Declared infecund (respondent or partner(s))"
     6 "Never had sex"
     7 "Man declared infecund"
     8 "Man has no partner"
;
label define MV603   
   100 "Wanted now"
   101 "Months: 1"
   199 "Months: number missing"
   201 "Years: 1"
   299 "Years: number missing"
   993 "After marriage"
   994 "Soon, now"
   996 "Other, non-numeric"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV604   
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
;
label define MV605   
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized (respondent or partner(s))"
     7 "Declared infecund (respondent or partner(s))"
     8 "Never had sex"
;
label define MV613   
    96 "Non-numeric response"
    98 "Don't know"
;
label define MV614   
     6 "6+"
     7 "Non-numeric response"
;
label define MV616   
   100 "Wanted now"
   101 "Months: 1"
   199 "Months: number missing"
   201 "Years: 1"
   299 "Years: number missing"
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "Don't know"
;
label define MV621   
     1 "Both want same"
     2 "Wife wants more"
     3 "Wife wants fewer"
     8 "Don't know"
;
label define MV627   
    96 "Other"
    98 "Don't know"
;
label define MV628   
    96 "Other"
    98 "Don't know"
;
label define MV629   
    96 "Other"
    98 "Don't know"
;
label define MV631   
     1 "Big problem"
     2 "Small problem"
     3 "No problem"
     4 "Says she can't get pregnant/not having sex"
;
label define MV633A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV634A  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634B  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634C  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634D  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV714   
     0 "No"
     1 "Yes"
;
label define MV714A  
     0 "No"
     1 "Yes"
;
label define MV716   
     0 "Not working/ Unemployed/ student/ retired"
     1 "Armed forces"
    11 "Legislators, senior officials and managers"
    12 "Corporate Managers"
    13 "General Managers"
    21 "Physical, Mathematical and Engineering Science Professionals"
    22 "Life Science and Health Professionals"
    23 "Teaching Professionals"
    24 "Other Professionals (business, lawyers, social workers)"
    31 "Physical and Engineering science Associate Professionals"
    32 "Life Science and Health Associate Professionals"
    33 "Teaching Associate Professionals"
    34 "Other Associate Professionals"
    41 "Office Clerks"
    42 "Customer Service Clerks"
    51 "Personal and Protective Service Workers"
    52 "Models, Salespersons and Demonstrators"
    61 "Market - Oriented Skilled Agricultural and Fishery Workers"
    62 "Subsistence Agricultural and Fishery Workers"
    71 "Miners/ constructors/ electricians"
    72 "Metal, Machinery and Related Workers/ mechanics"
    73 "Precision workers in metal and related materials"
    74 "Food processing and related workers"
    81 "Stationery Plant and Related Operators"
    82 "Machine Operators and Assemblers"
    83 "Drivers and Mobile Equipment Operators"
    90 "General Laborers"
    91 "Sales and Service Elementary Occupations"
    92 "Agriculture, Fishery and Related Laborers"
    93 "Laborers in mining, construction"
    96 "Other"
    98 "Don't know"
;
label define MV717   
     0 "Not working"
     1 "Professional/technical/managerial"
     2 "Clerical"
     3 "Sales"
     4 "Agriculture - self employed"
     5 "Agriculture - employee"
     6 "Household and domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    96 "Other"
    98 "Don't know"
;
label define MV719   
     1 "For family member"
     2 "For someone else"
     3 "Self-employed"
;
label define MV721   
     1 "At home"
     2 "Away"
;
label define MV731   
     0 "No"
     1 "In the past year"
     2 "Currently working"
;
label define MV732   
     1 "All year"
     2 "Seasonal"
     3 "Occasional"
;
label define MV739   
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
;
label define MV740   
     0 "Own land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
;
label define MV741   
     0 "Not paid"
     1 "Cash only"
     2 "Cash and in-kind"
     3 "In-kind only"
;
label define MV743A  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Other"
     8 "Don't know/depends"
;
label define MV743B  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Other"
     8 "Don't know/depends"
;
label define MV743C  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743D  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743E  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743F  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743G  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV744A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV745A  
     0 "Does not own"
     1 "Alone only"
     2 "Jointly only"
     3 "Both alone and jointly"
;
label define MV745B  
     0 "Does not own"
     1 "Alone only"
     2 "Jointly only"
     3 "Both alone and jointly"
;
label define MV747A  
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV747B  
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV750   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV751   
     0 "No"
     1 "Yes"
;
label define MV754BP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754CP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754DP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754JP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754WP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV756   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV762AA 
     0 "No"
     1 "Yes"
;
label define MV762AB 
     0 "No"
     1 "Yes"
;
label define MV762AC 
     0 "No"
     1 "Yes"
;
label define MV762AD 
     0 "No"
     1 "Yes"
;
label define MV762AE 
     0 "No"
     1 "Yes"
;
label define MV762AF 
     0 "No"
     1 "Yes"
;
label define MV762AG 
     0 "No"
     1 "Yes"
;
label define MV762AH 
     0 "No"
     1 "Yes"
;
label define MV762AI 
     0 "No"
     1 "Yes"
;
label define MV762AJ 
     0 "No"
     1 "Yes"
;
label define MV762AK 
     0 "No"
     1 "Yes"
;
label define MV762AL 
     0 "No"
     1 "Yes"
;
label define MV762AM 
     0 "No"
     1 "Yes"
;
label define MV762AN 
     0 "No"
     1 "Yes"
;
label define MV762AO 
     0 "No"
     1 "Yes"
;
label define MV762AP 
     0 "No"
     1 "Yes"
;
label define MV762AQ 
     0 "No"
     1 "Yes"
;
label define MV762AR 
     0 "No"
     1 "Yes"
;
label define MV762AS 
     0 "No"
     1 "Yes"
;
label define MV762AT 
     0 "No"
     1 "Yes"
;
label define MV762AU 
     0 "No"
     1 "Yes"
;
label define MV762AV 
     0 "No"
     1 "Yes"
;
label define MV762AW 
     0 "No"
     1 "Yes"
;
label define MV762AX 
     0 "No"
     1 "Yes"
;
label define MV762AZ 
     0 "No"
     1 "Yes: don't know"
;
label define MV762BA 
     0 "No"
     1 "Yes"
;
label define MV762BB 
     0 "No"
     1 "Yes"
;
label define MV762BC 
     0 "No"
     1 "Yes"
;
label define MV762BD 
     0 "No"
     1 "Yes"
;
label define MV762BE 
     0 "No"
     1 "Yes"
;
label define MV762BF 
     0 "No"
     1 "Yes"
;
label define MV762BG 
     0 "No"
     1 "Yes"
;
label define MV762BH 
     0 "No"
     1 "Yes"
;
label define MV762BI 
     0 "No"
     1 "Yes"
;
label define MV762BJ 
     0 "No"
     1 "Yes"
;
label define MV762BK 
     0 "No"
     1 "Yes"
;
label define MV762BL 
     0 "No"
     1 "Yes"
;
label define MV762BM 
     0 "No"
     1 "Yes"
;
label define MV762BN 
     0 "No"
     1 "Yes"
;
label define MV762BO 
     0 "No"
     1 "Yes"
;
label define MV762BP 
     0 "No"
     1 "Yes"
;
label define MV762BQ 
     0 "No"
     1 "Yes"
;
label define MV762BR 
     0 "No"
     1 "Yes"
;
label define MV762BS 
     0 "No"
     1 "Yes"
;
label define MV762BT 
     0 "No"
     1 "Yes"
;
label define MV762BU 
     0 "No"
     1 "Yes"
;
label define MV762BV 
     0 "No"
     1 "Yes"
;
label define MV762BW 
     0 "No"
     1 "Yes"
;
label define MV762BX 
     0 "No"
     1 "Yes"
;
label define MV762BZ 
     0 "No"
     1 "Yes: don't know"
;
label define MV763A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV766A  
    98 "Don't know"
;
label define MV766B  
    98 "Don't know"
;
label define MV767A  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV767B  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV767C  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV768A  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV768B  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV768C  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV769   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV769A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV770   
     0 "No"
     1 "Yes"
;
label define MV770A  
     0 "No"
     1 "Yes"
;
label define MV770B  
     0 "No"
     1 "Yes"
;
label define MV770C  
     0 "No"
     1 "Yes"
;
label define MV770D  
     0 "No"
     1 "Yes"
;
label define MV770E  
     0 "No"
     1 "Yes"
;
label define MV770F  
     0 "No"
     1 "Yes"
;
label define MV770G  
     0 "No"
     1 "Yes"
;
label define MV770H  
     0 "No"
     1 "Yes"
;
label define MV770I  
     0 "No"
     1 "Yes"
;
label define MV770J  
     0 "No"
     1 "Yes"
;
label define MV770K  
     0 "No"
     1 "Yes"
;
label define MV770L  
     0 "No"
     1 "Yes"
;
label define MV770M  
     0 "No"
     1 "Yes"
;
label define MV770N  
     0 "No"
     1 "Yes"
;
label define MV770O  
     0 "No"
     1 "Yes"
;
label define MV770P  
     0 "No"
     1 "Yes"
;
label define MV770Q  
     0 "No"
     1 "Yes"
;
label define MV770R  
     0 "No"
     1 "Yes"
;
label define MV770S  
     0 "No"
     1 "Yes"
;
label define MV770T  
     0 "No"
     1 "Yes"
;
label define MV770U  
     0 "No"
     1 "Yes"
;
label define MV770V  
     0 "No"
     1 "Yes"
;
label define MV770W  
     0 "No"
     1 "Yes"
;
label define MV770X  
     0 "No"
     1 "Yes"
;
label define MV774A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV774B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV774C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV775   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV777   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV778   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV779   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV780   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV781   
     0 "No"
     1 "Yes"
;
label define MV783   
     0 "No"
     1 "Yes"
;
label define MV784A  
     0 "No"
     1 "Yes"
;
label define MV784B  
     0 "No"
     1 "Yes"
;
label define MV784C  
     0 "No"
     1 "Yes"
;
label define MV784D  
     0 "No"
     1 "Yes"
;
label define MV784E  
     0 "No"
     1 "Yes"
;
label define MV784F  
     0 "No"
     1 "Yes"
;
label define MV784G  
     0 "No"
     1 "Yes"
;
label define MV784H  
     0 "No"
     1 "Yes"
;
label define MV784I  
     0 "No"
     1 "Yes"
;
label define MV784J  
     0 "No"
     1 "Yes"
;
label define MV784K  
     0 "No"
     1 "Yes"
;
label define MV784L  
     0 "No"
     1 "Yes"
;
label define MV784M  
     0 "No"
     1 "Yes"
;
label define MV784N  
     0 "No"
     1 "Yes"
;
label define MV784O  
     0 "No"
     1 "Yes"
;
label define MV784P  
     0 "No"
     1 "Yes"
;
label define MV784Q  
     0 "No"
     1 "Yes"
;
label define MV784R  
     0 "No"
     1 "Yes"
;
label define MV784S  
     0 "No"
     1 "Yes"
;
label define MV784T  
     0 "No"
     1 "Yes"
;
label define MV784U  
     0 "No"
     1 "Yes"
;
label define MV784V  
     0 "No"
     1 "Yes"
;
label define MV784X  
     0 "No"
     1 "Yes"
;
label define MV785   
     0 "No"
     1 "Yes"
;
label define MV791   
     0 "No"
     1 "Yes"
;
label define MV793   
     0 "No"
     1 "Yes"
;
label define MV793A  
     0 "No"
     1 "Yes"
;
label define MV793B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV820   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV822   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV823   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV824   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV825   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV826   
     1 "Less than 12 months"
     2 "12-23 months"
     3 "2 years or more"
;
label define MV826A  
    95 "Two or more years"
    98 "Don't know"
;
label define MV827   
     1 "Asked for the test"
     2 "Offered and accepted"
     3 "Required"
;
label define MV828   
     0 "No"
     1 "Yes"
;
label define MV829   
    11 "Government hospital"
    12 "Government health center"
    13 "Stand-alone VCT center"
    14 "Government primary health care clinic"
    15 "Outreach point"
    16 "Public Mobile clinic"
    17 "Public School-based clinic"
    18 "Other public"
    21 "Private hospital, clinic, doctor"
    22 "Private Stand-alone VCT center"
    23 "Private Pharmacy"
    24 "Private Mobile clinic"
    25 "Private Field worker"
    26 "Private School based clinic"
    27 "Other private medical"
    31 "Home"
    32 "Correctional facility"
    96 "Other"
;
label define MV832B  
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV832C  
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV833A  
     0 "No"
     1 "Yes"
;
label define MV833B  
     0 "No"
     1 "Yes"
;
label define MV833C  
     0 "No"
     1 "Yes"
;
label define MV834A  
    95 "95+"
    98 "Don't know"
;
label define MV834B  
    95 "95+"
    98 "Don't know"
;
label define MV834C  
    95 "95+"
    98 "Don't know"
;
label define MV835A  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV835B  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV835C  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV836   
    95 "95+"
    98 "Don't know"
;
label define MV837   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV844   
     0 "No"
     1 "Yes"
     8 "Don't know anyone with AIDS"
;
label define MV845   
     0 "No"
     1 "Yes"
;
label define MV846   
     0 "No"
     1 "Yes"
;
label define MV847   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/no opinion"
;
label define MV848   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/no opinion"
;
label define MV849   
     0 "No"
     1 "Yes"
     8 "Don't know/depends"
;
label define MV851A  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851B  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851C  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851D  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851E  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851F  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851G  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851H  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851I  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851J  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851K  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851L  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV852A  
   100 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV852B  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV852C  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV853A  
    95 "95+"
    98 "Don't know"
;
label define MV853B  
    95 "95+"
    98 "Don't know"
;
label define MV853C  
    95 "95+"
    98 "Don't know"
;
label define MV854A  
     0 "No"
     1 "Yes"
;
label define MV854B  
     0 "No"
     1 "Yes"
;
label define SM114   
     1 "Afrikaans"
     2 "Damara/Nama"
     3 "English"
     4 "Herero"
     5 "Kwangali"
     6 "Lozi"
     7 "Oshiwambo"
     8 "San"
    96 "Other"
;
label define SM218A  
     0 "No"
     1 "Yes"
;
label define SM614F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM714A  
     0 "No"
     1 "Yes"
;
label define SM714B  
     1 "Positive"
     2 "Negative"
;
label define SM714C  
     0 "No"
     1 "Yes"
;
label define SM714D  
     0 "No"
     1 "Yes"
     3 "No partner"
;
label define SM715A  
     1 "Individual"
     2 "Couple"
;
label define SM715B  
     0 "No"
     1 "Yes"
;
label define SM715C  
     1 "Partner refuses"
     2 "Distance to service delivery"
     3 "No time"
     4 "Service delivery hours"
     6 "Other"
;
label define SM715E  
     0 "No"
     1 "Yes"
;
label define SM715F  
     1 "Transportation cost"
     2 "Religious reasons"
     3 "Food/nutritional issues"
     4 "Side effects"
     5 "Fear of being seen at ARV clinic"
     6 "Other"
;
label define SM804A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM804B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM804CA 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM804CB 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM804CC 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM804CD 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM804CE 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM804CF 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM804CX 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM804CY 
     0 "No"
     1 "Yes"
     8 "Not sure"
;
label define SM804FA 
     0 "No"
     1 "Yes"
;
label define SM804FB 
     0 "No"
     1 "Yes"
;
label define SM804FC 
     0 "No"
     1 "Yes"
;
label define SM804FD 
     0 "No"
     1 "Yes"
;
label define SM804FE 
     0 "No"
     1 "Yes"
;
label define SM804FF 
     0 "No"
     1 "Yes"
;
label define SM804FX 
     0 "No"
     1 "Yes"
;
label define SM804FZ 
     0 "No"
     1 "Yes"
;
label define SM811A  
     0 "No"
     1 "Yes"
;
label define SM811C  
     0 "No"
     1 "Yes"
;
label define SM811F  
     0 "No"
     1 "Yes"
;
label define SM811G  
    98 "Dont know/not sure"
;
label define SM811H  
    98 "Dont know/not sure"
;
label define SM813A  
     1 "No"
     2 "Yes at work"
     3 "Yes other physical activity"
;
label define SM813B  
     8 "Dont know/not sure"
;
label define SM813E  
    99 "Missing"
;
label define SM813F  
     8 "Dont know/not sure"
;
label define SM813G  
     7 "7+"
     8 "Dont know/not sure"
;
label define SM813H  
     7 "7+"
     8 "Dont know/not sure"
;
label define SM813I  
     7 "7+"
     8 "Dont know/not sure"
;
label define SM813M  
     1 "All the time"
     2 "Sometime"
     3 "Never"
     4 "Have not been in vehicle in past 30 days"
     5 "No seatbelt in car"
     8 "Dont know/not sure"
;
label define SM813O  
     0 "No"
     1 "Yes"
;
label define SM813P  
     0 "No"
     1 "Yes"
     8 "Dont know"
;
label define SM813Q  
     0 "No"
     1 "Yes"
;
label define SM813R  
     0 "No"
     1 "Yes"
;
label define SM813S  
     0 "No"
     1 "Yes"
     8 "Dont know/not sure"
;
label define SM813T  
     0 "No"
     1 "Yes"
     8 "Dont know/not sure"
;
label define SM813V  
     0 "No"
     1 "Yes"
;
label define MV044   
     0 "Man not selected"
     1 "Man selected and interviewed"
     2 "Man selected, but privacy not possible"
     3 "Man selected, but not interviewed"
;
label define DM101A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define DM101B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define DM101C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define DM101D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define DM101E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define DM101F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define DM102   
    99 "Missing"
;
label define DM103A  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define DM103B  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define DM103C  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define DM104   
     0 "No"
     1 "Yes"
;
label define DM105A  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define DM105B  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define DM105C  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define DM105D  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define DM105E  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define DM105F  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define DM105H  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define DM105I  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define DM105J  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define DM105K  
     0 "Never"
     1 "Often"
     2 "Sometimes"
     3 "Yes, but not in the last 12 months"
     4 "Yes, but frequency in last 12 months missing"
;
label define DM106   
     0 "No"
     1 "Yes"
;
label define DM107   
     0 "No"
     1 "Yes"
;
label define DM108   
     0 "No"
     1 "Yes"
;
label define DM109   
    95 "Before union"
    96 "After separation/divorce"
    98 "Don't know"
;
label define DM110A  
     0 "No"
     1 "Yes"
;
label define DM110B  
     0 "No"
     1 "Yes"
;
label define DM110D  
     0 "No"
     1 "Yes"
;
label define DM111   
     0 "No"
     1 "Yes"
;
label define DM112   
     0 "No"
     1 "Yes"
;
label define DM112A  
     0 "Not at all in last 12 months"
     1 "Often"
     2 "Sometimes"
     8 "Don't know"
;
label define DM113   
     0 "No"
     1 "Yes"
;
label define DM114   
     0 "Never"
     1 "Often"
     2 "Sometimes"
;
label define DM115B  
     0 "No"
     1 "Yes"
;
label define DM115C  
     0 "No"
     1 "Yes"
;
label define DM115D  
     0 "No"
     1 "Yes"
;
label define DM115F  
     0 "No"
     1 "Yes"
;
label define DM115G  
     0 "No"
     1 "Yes"
;
label define DM115K  
     0 "No"
     1 "Yes"
;
label define DM115L  
     0 "No"
     1 "Yes"
;
label define DM115O  
     0 "No"
     1 "Yes"
;
label define DM115P  
     0 "No"
     1 "Yes"
;
label define DM115Q  
     0 "No"
     1 "Yes"
;
label define DM115V  
     0 "No"
     1 "Yes"
;
label define DM115W  
     0 "No"
     1 "Yes"
;
label define DM115X  
     0 "No"
     1 "Yes"
;
label define DM115Y  
     0 "Someone physically hurt respondent"
     1 "None of these people ever physically hurt respondent"
     6 "No response to question"
;
label define DM115XE 
     0 "No"
     1 "Yes"
;
label define DM117A  
     0 "Not at all"
     1 "Often"
     2 "Sometimes"
;
label define DM119H  
     0 "No"
     1 "Yes"
;
label define DM119I  
     0 "No"
     1 "Yes"
;
label define DM119J  
     0 "No"
     1 "Yes"
;
label define DM119K  
     0 "No"
     1 "Yes"
;
label define DM119U  
     0 "No"
     1 "Yes"
;
label define DM119X  
     0 "No"
     1 "Yes"
;
label define DM119XB 
     0 "No"
     1 "Yes"
;
label define DM119XD 
     0 "No"
     1 "Yes"
;
label define DM119XE 
     0 "No"
     1 "Yes"
;
label define DM119XF 
     0 "No"
     1 "Yes"
;
label define DM119XG 
     0 "No"
     1 "Yes"
;
label define DM119XH 
     0 "No"
     1 "Yes"
;
label define DM119Y  
     0 "Sought help from someone"
     1 "No help was sought"
;
label define DM121   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define DM122A  
     0 "No"
     1 "Yes, once"
     2 "Yes, more than once"
;
label define DM122B  
     0 "No"
     1 "Yes, once"
     2 "Yes, more than once"
;
label define DM122C  
     0 "No"
     1 "Yes, once"
     2 "Yes, more than once"
;
label define DM124   
     0 "No"
     1 "Yes"
     6 "Refused to answer/no response"
;
label define DM125   
     0 "No"
     1 "Yes"
     6 "Refused to answer/no response"
;
label define DM126   
    98 "Don't know"
;
label define DM127   
     1 "Current husband/partner"
     2 "Former husband/partner"
     3 "Current/former girlfriend"
     4 "Father/step father"
     5 "Brother/step brother"
     6 "Other relative"
     7 "In-law"
     8 "Own friend/acquaintance"
     9 "Family friend"
    10 "Teacher"
    11 "Employer/someone at work"
    12 "Police/soldier"
    13 "Priest/religious leader"
    14 "Stranger"
    96 "Other"
;
label define DM128   
     0 "No"
     1 "Yes"
;
label define DM129   
     0 "Never afraid"
     1 "Most of the time afraid"
     2 "Sometimes afraid"
;
label define DM130A  
     0 "Never"
     1 "0-11 months ago"
     2 "12+ months ago"
     3 "Yes, but don't remember when"
     4 "Yes, but frequency in last 12 months missing"
;
label define DM130B  
     0 "Never"
     1 "0-11 months ago"
     2 "12+ months ago"
     3 "Yes, but don't remember when"
     4 "Yes, but frequency in last 12 months missing"
;
label define SMLANGUA
     1 "Afrikaans"
     2 "Damara/Nama"
     3 "English"
     4 "Herero"
     5 "Kwangali"
     6 "Lozi"
     7 "Oshiwambo"
     8 "Other"
;
label define SMLANGRESP
     1 "Afrikaans"
     2 "Damara/Nama"
     3 "English"
     4 "Herero"
     5 "Kwangali"
     6 "Lozi"
     7 "Oshiwambo"
     8 "Other"
;
label define SMLANGINT
     1 "Afrikaans"
     2 "Damara/Nama"
     3 "English"
     4 "Herero"
     5 "Kwangali"
     6 "Lozi"
     7 "Oshiwambo"
     8 "Other"
;
label define SMTRANSL
     0 "No"
     1 "Yes"
;

#delimit cr
label values mv013    MV013   
label values mv014    MV014   
label values mv015    MV015   
label values mv022    MV022   
label values mv023    MV023   
label values mv024    MV024   
label values mv025    MV025   
label values mv026    MV026   
label values mv034_1  MV034   
label values mv034_2  MV034   
label values mv034_3  MV034   
label values mv034_4  MV034   
label values mv034_5  MV034   
label values mv034_6  MV034   
label values mv034_7  MV034   
label values mv034_8  MV034   
label values mv034a_1 MV034A  
label values mv034a_2 MV034A  
label values mv034a_3 MV034A  
label values mv034a_4 MV034A  
label values mv034a_5 MV034A  
label values mv034a_6 MV034A  
label values mv034a_7 MV034A  
label values mv034a_8 MV034A  
label values mv035    MV035   
label values mv803    MV803   
label values mv101    MV101   
label values mv102    MV102   
label values mv103    MV103   
label values mv104    MV104   
label values mv105    MV105   
label values mv106    MV106   
label values mv107    MV107   
label values mv130    MV130   
label values mv133    MV133   
label values mv134    MV134   
label values mv135    MV135   
label values mv149    MV149   
label values mv150    MV150   
label values mv151    MV151   
label values mv152    MV152   
label values mv155    MV155   
label values mv156    MV156   
label values mv157    MV157   
label values mv158    MV158   
label values mv159    MV159   
label values mv167    MV167   
label values mv168    MV168   
label values mv190    MV190   
label values mv213    MV213   
label values mv217    MV217   
label values mv225    MV225   
label values mv246    MV246   
label values mv248    MV248   
label values mv249    MV249   
label values mv250    MV250   
label values mv251    MV251   
label values mv252    MV252   
label values mv301    MV301   
label values mv302    MV302   
label values m304a_01 M304A   
label values m304a_02 M304A   
label values m304a_03 M304A   
label values m304a_04 M304A   
label values m304a_05 M304A   
label values m304a_06 M304A   
label values m304a_07 M304A   
label values m304a_08 M304A   
label values m304a_09 M304A   
label values m304a_10 M304A   
label values m304a_11 M304A   
label values m304a_12 M304A   
label values m304a_13 M304A   
label values m304a_14 M304A   
label values m304a_15 M304A   
label values m304a_16 M304A   
label values m304a_17 M304A   
label values m304a_18 M304A   
label values m304a_19 M304A   
label values m304a_20 M304A   
label values mv304_01 MV304   
label values mv304_02 MV304   
label values mv304_03 MV304   
label values mv304_04 MV304   
label values mv304_05 MV304   
label values mv304_06 MV304   
label values mv304_07 MV304   
label values mv304_08 MV304   
label values mv304_09 MV304   
label values mv304_10 MV304   
label values mv304_11 MV304   
label values mv304_12 MV304   
label values mv304_13 MV304   
label values mv304_14 MV304   
label values mv304_15 MV304   
label values mv304_16 MV304   
label values mv304_17 MV304   
label values mv304_18 MV304   
label values mv304_19 MV304   
label values mv304_20 MV304   
label values mv305_01 MV305   
label values mv305_02 MV305   
label values mv305_03 MV305   
label values mv305_04 MV305   
label values mv305_05 MV305   
label values mv305_06 MV305   
label values mv305_07 MV305   
label values mv305_08 MV305   
label values mv305_09 MV305   
label values mv305_10 MV305   
label values mv305_11 MV305   
label values mv305_12 MV305   
label values mv305_13 MV305   
label values mv305_14 MV305   
label values mv305_15 MV305   
label values mv305_16 MV305   
label values mv305_17 MV305   
label values mv305_18 MV305   
label values mv305_19 MV305   
label values mv305_20 MV305   
label values mv307_01 MV307   
label values mv307_02 MV307   
label values mv307_03 MV307   
label values mv307_04 MV307   
label values mv307_05 MV307   
label values mv307_06 MV307   
label values mv307_07 MV307   
label values mv307_08 MV307   
label values mv307_09 MV307   
label values mv307_10 MV307   
label values mv307_11 MV307   
label values mv307_12 MV307   
label values mv307_13 MV307   
label values mv307_14 MV307   
label values mv307_15 MV307   
label values mv307_16 MV307   
label values mv307_17 MV307   
label values mv307_18 MV307   
label values mv307_19 MV307   
label values mv307_20 MV307   
label values mv312    MV312   
label values mv313    MV313   
label values mv323a   MV323A  
label values mv325b   MV325B  
label values mv372a   MV372A  
label values mv384a   MV384A  
label values mv384b   MV384B  
label values mv384c   MV384C  
label values mv395    MV395   
label values mv396    MV396   
label values mv3a09b  MV3A09B 
label values mv3b17   MV3B17  
label values mv3b25a  MV3B25A 
label values mv3b25b  MV3B25B 
label values mv463a   MV463A  
label values mv463b   MV463B  
label values mv463c   MV463C  
label values mv463d   MV463D  
label values mv463e   MV463E  
label values mv463f   MV463F  
label values mv463g   MV463G  
label values mv463x   MV463X  
label values mv463z   MV463Z  
label values mv464    MV464   
label values mv474    MV474   
label values mv474a   MV474A  
label values mv474b   MV474B  
label values mv474c   MV474C  
label values mv474d   MV474D  
label values mv474e   MV474E  
label values mv474f   MV474F  
label values mv474g   MV474G  
label values mv474h   MV474H  
label values mv474i   MV474I  
label values mv474j   MV474J  
label values mv474x   MV474X  
label values mv474z   MV474Z  
label values mv475    MV475   
label values mv476    MV476   
label values mv477    MV477   
label values mv478    MV478   
label values mv479    MV479   
label values mv480    MV480   
label values mv481    MV481   
label values mv481a   MV481A  
label values mv481b   MV481B  
label values mv481c   MV481C  
label values mv481d   MV481D  
label values mv481e   MV481E  
label values mv481f   MV481F  
label values mv481g   MV481G  
label values mv481h   MV481H  
label values mv481x   MV481X  
label values mv482a   MV482A  
label values mv482b   MV482B  
label values mv482c   MV482C  
label values mv483    MV483   
label values mv483a   MV483A  
label values mv483b   MV483B  
label values mv483c   MV483C  
label values mv501    MV501   
label values mv502    MV502   
label values mv503    MV503   
label values mv504    MV504   
label values mv510    MV510   
label values mv513    MV513   
label values mv525    MV525   
label values mv527    MV527   
label values mv528    MV528   
label values mv529    MV529   
label values mv531    MV531   
label values mv532    MV532   
label values mv535    MV535   
label values mv536    MV536   
label values mv541    MV541   
label values mv602    MV602   
label values mv603    MV603   
label values mv604    MV604   
label values mv605    MV605   
label values mv613    MV613   
label values mv614    MV614   
label values mv616    MV616   
label values mv621    MV621   
label values mv627    MV627   
label values mv628    MV628   
label values mv629    MV629   
label values mv631    MV631   
label values mv633a   MV633A  
label values mv633b   MV633B  
label values mv633c   MV633C  
label values mv633d   MV633D  
label values mv633e   MV633E  
label values mv633f   MV633F  
label values mv633g   MV633G  
label values mv634a   MV634A  
label values mv634b   MV634B  
label values mv634c   MV634C  
label values mv634d   MV634D  
label values mv714    MV714   
label values mv714a   MV714A  
label values mv716    MV716   
label values mv717    MV717   
label values mv719    MV719   
label values mv721    MV721   
label values mv731    MV731   
label values mv732    MV732   
label values mv739    MV739   
label values mv740    MV740   
label values mv741    MV741   
label values mv743a   MV743A  
label values mv743b   MV743B  
label values mv743c   MV743C  
label values mv743d   MV743D  
label values mv743e   MV743E  
label values mv743f   MV743F  
label values mv743g   MV743G  
label values mv744a   MV744A  
label values mv744b   MV744B  
label values mv744c   MV744C  
label values mv744d   MV744D  
label values mv744e   MV744E  
label values mv745a   MV745A  
label values mv745b   MV745B  
label values mv747a   MV747A  
label values mv747b   MV747B  
label values mv750    MV750   
label values mv751    MV751   
label values mv754bp  MV754BP 
label values mv754cp  MV754CP 
label values mv754dp  MV754DP 
label values mv754jp  MV754JP 
label values mv754wp  MV754WP 
label values mv756    MV756   
label values mv761    MV761   
label values mv761b   MV761B  
label values mv761c   MV761C  
label values mv762aa  MV762AA 
label values mv762ab  MV762AB 
label values mv762ac  MV762AC 
label values mv762ad  MV762AD 
label values mv762ae  MV762AE 
label values mv762af  MV762AF 
label values mv762ag  MV762AG 
label values mv762ah  MV762AH 
label values mv762ai  MV762AI 
label values mv762aj  MV762AJ 
label values mv762ak  MV762AK 
label values mv762al  MV762AL 
label values mv762am  MV762AM 
label values mv762an  MV762AN 
label values mv762ao  MV762AO 
label values mv762ap  MV762AP 
label values mv762aq  MV762AQ 
label values mv762ar  MV762AR 
label values mv762as  MV762AS 
label values mv762at  MV762AT 
label values mv762au  MV762AU 
label values mv762av  MV762AV 
label values mv762aw  MV762AW 
label values mv762ax  MV762AX 
label values mv762az  MV762AZ 
label values mv762ba  MV762BA 
label values mv762bb  MV762BB 
label values mv762bc  MV762BC 
label values mv762bd  MV762BD 
label values mv762be  MV762BE 
label values mv762bf  MV762BF 
label values mv762bg  MV762BG 
label values mv762bh  MV762BH 
label values mv762bi  MV762BI 
label values mv762bj  MV762BJ 
label values mv762bk  MV762BK 
label values mv762bl  MV762BL 
label values mv762bm  MV762BM 
label values mv762bn  MV762BN 
label values mv762bo  MV762BO 
label values mv762bp  MV762BP 
label values mv762bq  MV762BQ 
label values mv762br  MV762BR 
label values mv762bs  MV762BS 
label values mv762bt  MV762BT 
label values mv762bu  MV762BU 
label values mv762bv  MV762BV 
label values mv762bw  MV762BW 
label values mv762bx  MV762BX 
label values mv762bz  MV762BZ 
label values mv763a   MV763A  
label values mv763b   MV763B  
label values mv763c   MV763C  
label values mv763d   MV763D  
label values mv763e   MV763E  
label values mv763f   MV763F  
label values mv763g   MV763G  
label values mv766a   MV766A  
label values mv766b   MV766B  
label values mv767a   MV767A  
label values mv767b   MV767B  
label values mv767c   MV767C  
label values mv768a   MV768A  
label values mv768b   MV768B  
label values mv768c   MV768C  
label values mv769    MV769   
label values mv769a   MV769A  
label values mv770    MV770   
label values mv770a   MV770A  
label values mv770b   MV770B  
label values mv770c   MV770C  
label values mv770d   MV770D  
label values mv770e   MV770E  
label values mv770f   MV770F  
label values mv770g   MV770G  
label values mv770h   MV770H  
label values mv770i   MV770I  
label values mv770j   MV770J  
label values mv770k   MV770K  
label values mv770l   MV770L  
label values mv770m   MV770M  
label values mv770n   MV770N  
label values mv770o   MV770O  
label values mv770p   MV770P  
label values mv770q   MV770Q  
label values mv770r   MV770R  
label values mv770s   MV770S  
label values mv770t   MV770T  
label values mv770u   MV770U  
label values mv770v   MV770V  
label values mv770w   MV770W  
label values mv770x   MV770X  
label values mv774a   MV774A  
label values mv774b   MV774B  
label values mv774c   MV774C  
label values mv775    MV775   
label values mv777    MV777   
label values mv778    MV778   
label values mv779    MV779   
label values mv780    MV780   
label values mv781    MV781   
label values mv783    MV783   
label values mv784a   MV784A  
label values mv784b   MV784B  
label values mv784c   MV784C  
label values mv784d   MV784D  
label values mv784e   MV784E  
label values mv784f   MV784F  
label values mv784g   MV784G  
label values mv784h   MV784H  
label values mv784i   MV784I  
label values mv784j   MV784J  
label values mv784k   MV784K  
label values mv784l   MV784L  
label values mv784m   MV784M  
label values mv784n   MV784N  
label values mv784o   MV784O  
label values mv784p   MV784P  
label values mv784q   MV784Q  
label values mv784r   MV784R  
label values mv784s   MV784S  
label values mv784t   MV784T  
label values mv784u   MV784U  
label values mv784v   MV784V  
label values mv784x   MV784X  
label values mv785    MV785   
label values mv791    MV791   
label values mv793    MV793   
label values mv793a   MV793A  
label values mv793b   MV793B  
label values mv820    MV820   
label values mv822    MV822   
label values mv823    MV823   
label values mv824    MV824   
label values mv825    MV825   
label values mv826    MV826   
label values mv826a   MV826A  
label values mv827    MV827   
label values mv828    MV828   
label values mv829    MV829   
label values mv832b   MV832B  
label values mv832c   MV832C  
label values mv833a   MV833A  
label values mv833b   MV833B  
label values mv833c   MV833C  
label values mv834a   MV834A  
label values mv834b   MV834B  
label values mv834c   MV834C  
label values mv835a   MV835A  
label values mv835b   MV835B  
label values mv835c   MV835C  
label values mv836    MV836   
label values mv837    MV837   
label values mv844    MV844   
label values mv845    MV845   
label values mv846    MV846   
label values mv847    MV847   
label values mv848    MV848   
label values mv849    MV849   
label values mv851a   MV851A  
label values mv851b   MV851B  
label values mv851c   MV851C  
label values mv851d   MV851D  
label values mv851e   MV851E  
label values mv851f   MV851F  
label values mv851g   MV851G  
label values mv851h   MV851H  
label values mv851i   MV851I  
label values mv851j   MV851J  
label values mv851k   MV851K  
label values mv851l   MV851L  
label values mv852a   MV852A  
label values mv852b   MV852B  
label values mv852c   MV852C  
label values mv853a   MV853A  
label values mv853b   MV853B  
label values mv853c   MV853C  
label values mv854a   MV854A  
label values mv854b   MV854B  
label values sm114    SM114   
label values sm218a   SM218A  
label values sm614f   SM614F  
label values sm714a   SM714A  
label values sm714b   SM714B  
label values sm714c   SM714C  
label values sm714d   SM714D  
label values sm715a   SM715A  
label values sm715b   SM715B  
label values sm715c   SM715C  
label values sm715e   SM715E  
label values sm715f   SM715F  
label values sm804a   SM804A  
label values sm804b   SM804B  
label values sm804ca  SM804CA 
label values sm804cb  SM804CB 
label values sm804cc  SM804CC 
label values sm804cd  SM804CD 
label values sm804ce  SM804CE 
label values sm804cf  SM804CF 
label values sm804cx  SM804CX 
label values sm804cy  SM804CY 
label values sm804fa  SM804FA 
label values sm804fb  SM804FB 
label values sm804fc  SM804FC 
label values sm804fd  SM804FD 
label values sm804fe  SM804FE 
label values sm804ff  SM804FF 
label values sm804fx  SM804FX 
label values sm804fz  SM804FZ 
label values sm811a   SM811A  
label values sm811c   SM811C  
label values sm811f   SM811F  
label values sm811g   SM811G  
label values sm811h   SM811H  
label values sm813a   SM813A  
label values sm813b   SM813B  
label values sm813f   SM813F  
label values sm813g   SM813G  
label values sm813h   SM813H  
label values sm813i   SM813I  
label values sm813m   SM813M  
label values sm813o   SM813O  
label values sm813p   SM813P  
label values sm813q   SM813Q  
label values sm813r   SM813R  
label values sm813s   SM813S  
label values sm813t   SM813T  
label values sm813v   SM813V  
label values mv044    MV044   
label values dm101a   DM101A  
label values dm101b   DM101B  
label values dm101c   DM101C  
label values dm101d   DM101D  
label values dm101e   DM101E  
label values dm101f   DM101F  
label values dm103a   DM103A  
label values dm103b   DM103B  
label values dm103c   DM103C  
label values dm104    DM104   
label values dm105a   DM105A  
label values dm105b   DM105B  
label values dm105c   DM105C  
label values dm105d   DM105D  
label values dm105e   DM105E  
label values dm105f   DM105F  
label values dm105h   DM105H  
label values dm105i   DM105I  
label values dm105j   DM105J  
label values dm105k   DM105K  
label values dm106    DM106   
label values dm107    DM107   
label values dm108    DM108   
label values dm109    DM109   
label values dm110a   DM110A  
label values dm110b   DM110B  
label values dm110d   DM110D  
label values dm111    DM111   
label values dm112    DM112   
label values dm112a   DM112A  
label values dm113    DM113   
label values dm114    DM114   
label values dm115b   DM115B  
label values dm115c   DM115C  
label values dm115d   DM115D  
label values dm115f   DM115F  
label values dm115g   DM115G  
label values dm115k   DM115K  
label values dm115l   DM115L  
label values dm115o   DM115O  
label values dm115p   DM115P  
label values dm115q   DM115Q  
label values dm115v   DM115V  
label values dm115w   DM115W  
label values dm115x   DM115X  
label values dm115y   DM115Y  
label values dm115xe  DM115XE 
label values dm117a   DM117A  
label values dm119h   DM119H  
label values dm119i   DM119I  
label values dm119j   DM119J  
label values dm119k   DM119K  
label values dm119u   DM119U  
label values dm119x   DM119X  
label values dm119xb  DM119XB 
label values dm119xd  DM119XD 
label values dm119xe  DM119XE 
label values dm119xf  DM119XF 
label values dm119xg  DM119XG 
label values dm119xh  DM119XH 
label values dm119y   DM119Y  
label values dm121    DM121   
label values dm122a   DM122A  
label values dm122b   DM122B  
label values dm122c   DM122C  
label values dm124    DM124   
label values dm125    DM125   
label values dm126    DM126   
label values dm127    DM127   
label values dm128    DM128   
label values dm129    DM129   
label values dm130a   DM130A  
label values dm130b   DM130B  
label values smlangua SMLANGUA
label values smlangresp SMLANGRESP
label values smlangint SMLANGINT
label values smtransl SMTRANSL
