---
title: "data_analysis"
author: "Shari Tian"
date: "2/28/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Packages

```{r}
library(tidyverse)
library(broom)
library(plm)
library(sf)
```


# Model

## Data

```{r}
zimbabwe <- readRDS("DHS_data/Zimbabwe/Zimbabwe_final.RDS")
```

```{r}
models <- function(outcome, country){
  df <- readRDS(paste0("DHS_data/", country, "/", country, "_final.RDS"))
  outcomes <- c("abortion", "conception", "start", "start_modern", "start_traditional",
                  "start_short", "start_long", "shortLong_switch", "longShort_switch", "modTrad_switch",
                  "tradMod_switch", "discontinuation")
  model_tibble <- tibble(model = list())
  for(outcome in outcomes){
    model <- lm(outcome ~ exposed_15 + time*exposed_15 + v001 + deaths + foreign_aid
                  + v501 + v013 + v025 + v149 + v190, data = df)
    model_tibble <- model_tibble %>% add_row(model = model)
  }
}
```


```{r}
zim_model <- lm(abortion ~ exposed_15 + time*exposed_15 + v001 + #deaths
                foreign_aid + v501 + v013 + v025 + v149 + v190, 
                data = zimbabwe)

tidy(zim_model)
```

```{r}
zim_model2 <- plm(abortion ~ exposed_15,
                  data = zimbabwe, 
                  index = c("v001", "caseid"),
                  model = "within")
tidy(zim_model2)
```

