infix using "C:\COUNTRIES\GH71\GHMR71FL.dct"

label variable mcaseid  "Case Identification"
label variable mv000    "Country code and phase"
label variable mv001    "Cluster number"
label variable mv002    "Household number"
label variable mv003    "Respondent's line number"
label variable mv004    "Ultimate area unit"
label variable mv005    "Men's sample weight (6 decimals)"
label variable mv006    "Month of interview"
label variable mv007    "Year of interview"
label variable mv008    "Date of interview (CMC)"
label variable mv009    "Month of birth"
label variable mv010    "Year of birth"
label variable mv011    "Date of birth (CMC)"
label variable mv012    "Current age"
label variable mv013    "Age in 5-year groups"
label variable mv014    "Completeness of age information"
label variable mv015    "Result of interview"
label variable mv016    "Day of interview"
label variable mv021    "Primary sampling unit"
label variable mv022    "Sample stratum number"
label variable mv023    "Sample domain"
label variable mv024    "Region"
label variable mv025    "Type of place of residence"
label variable mv026    "NA - De facto place of residence"
label variable mv027    "Number of visits"
label variable mv028    "Interviewer identification"
label variable mv029    "NA - Keyer identification"
label variable mv030    "Field supervisor"
label variable mv031    "Field editor"
label variable mv032    "NA - Office editor"
label variable mv034_1  "Line number of wife/partner"
label variable mv034_2  "Line number of wife/partner"
label variable mv034_3  "Line number of wife/partner"
label variable mv034_4  "Line number of wife/partner"
label variable mv034_5  "Line number of wife/partner"
label variable mv034_6  "Line number of wife/partner"
label variable mv034_7  "Line number of wife/partner"
label variable mv034_8  "Line number of wife/partner"
label variable mv034a_1 "NA - Wife or partner"
label variable mv034a_2 "NA - Wife or partner"
label variable mv034a_3 "NA - Wife or partner"
label variable mv034a_4 "NA - Wife or partner"
label variable mv034a_5 "NA - Wife or partner"
label variable mv034a_6 "NA - Wife or partner"
label variable mv034a_7 "NA - Wife or partner"
label variable mv034a_8 "NA - Wife or partner"
label variable mv034b_1 "Age of wife/partner"
label variable mv034b_2 "Age of wife/partner"
label variable mv034b_3 "Age of wife/partner"
label variable mv034b_4 "Age of wife/partner"
label variable mv034b_5 "Age of wife/partner"
label variable mv034b_6 "Age of wife/partner"
label variable mv034b_7 "Age of wife/partner"
label variable mv034b_8 "Age of wife/partner"
label variable mv035    "Number of wives/partners"
label variable mv801    "Time interview started (hhmm - 24 hour clock)"
label variable mv802    "Time interview ended (hhmm - 24 hour clock)"
label variable mv803    "Length of interview in minutes"
label variable mv101    "Region"
label variable mv102    "Type of place of residence"
label variable mv103    "NA - Childhood place of residence"
label variable mv104    "NA - Years lived in place of residence"
label variable mv105    "NA - Type of place of previous residence"
label variable mv106    "Educational level"
label variable mv107    "Highest year of education (at level in MV106)"
label variable mv130    "Religion"
label variable mv131    "Ethnicity"
label variable mv133    "Total number of years of education"
label variable mv134    "NA - De facto place of residence"
label variable mv135    "Usual resident or visitor"
label variable mv136    "Number of household members (total listed)"
label variable mv138    "Number of eligible men in household (de facto)"
label variable mv149    "Educational attainment"
label variable mv150    "Relationship to household head"
label variable mv151    "Sex of household head"
label variable mv152    "Age of household head"
label variable mv155    "Literacy"
label variable mv156    "NA - Ever participated in a literacy program (excluding primary school)"
label variable mv157    "Frequency of reading newspaper or magazine"
label variable mv158    "Frequency of listening to radio"
label variable mv159    "Frequency of watching television"
label variable mv167    "Times away from home in last 12 months"
label variable mv168    "Away for more than one month in last 12 months"
label variable mv190    "Wealth index"
label variable mv191    "Wealth index factor score (5 decimals)"
label variable mv201    "Total children ever born"
label variable mv202    "Sons at home"
label variable mv203    "Daughters at home"
label variable mv204    "Sons elsewhere"
label variable mv205    "Daughters elsewhere"
label variable mv206    "Sons who have died"
label variable mv207    "Daughters who have died"
label variable mv212    "Age of respondent at 1st birth"
label variable mv213    "Partner currently pregnant"
label variable mv217    "Knowledge of ovulatory cycle"
label variable mv218    "Number of living children"
label variable mv225    "NA - Most recent pregnancy wanted"
label variable mv245    "Number of women fathered children with"
label variable mv246    "NA - Married to mother when first child was born"
label variable mv247    "Age of most recent child"
label variable mv248    "Antenatal check-ups for the mother of most recent child"
label variable mv249    "Respondent present during check-ups for most recent child"
label variable mv250    "Place of birth of most recent child"
label variable mv251    "Reason for not delivering most recent child in health facility"
label variable mv252    "Amount a child should drink, when that child has diarrhea"
label variable mv301    "Knowledge of any contraceptive method"
label variable mv302    "NA - Ever use of any contraceptive method"
label variable m304a_01 "Type of contraceptive method"
label variable m304a_02 "Type of contraceptive method"
label variable m304a_03 "Type of contraceptive method"
label variable m304a_04 "Type of contraceptive method"
label variable m304a_05 "Type of contraceptive method"
label variable m304a_06 "Type of contraceptive method"
label variable m304a_07 "Type of contraceptive method"
label variable m304a_08 "Type of contraceptive method"
label variable m304a_09 "Type of contraceptive method"
label variable m304a_10 "Type of contraceptive method"
label variable m304a_11 "Type of contraceptive method"
label variable m304a_12 "Type of contraceptive method"
label variable m304a_13 "Type of contraceptive method"
label variable m304a_14 "Type of contraceptive method"
label variable m304a_15 "Type of contraceptive method"
label variable m304a_16 "Type of contraceptive method"
label variable m304a_17 "Type of contraceptive method"
label variable m304a_18 "Type of contraceptive method"
label variable m304a_19 "Type of contraceptive method"
label variable m304a_20 "Type of contraceptive method"
label variable mv304_01 "Knows contraceptive method"
label variable mv304_02 "Knows contraceptive method"
label variable mv304_03 "Knows contraceptive method"
label variable mv304_04 "Knows contraceptive method"
label variable mv304_05 "Knows contraceptive method"
label variable mv304_06 "Knows contraceptive method"
label variable mv304_07 "Knows contraceptive method"
label variable mv304_08 "Knows contraceptive method"
label variable mv304_09 "Knows contraceptive method"
label variable mv304_10 "Knows contraceptive method"
label variable mv304_11 "Knows contraceptive method"
label variable mv304_12 "Knows contraceptive method"
label variable mv304_13 "Knows contraceptive method"
label variable mv304_14 "Knows contraceptive method"
label variable mv304_15 "Knows contraceptive method"
label variable mv304_16 "Knows contraceptive method"
label variable mv304_17 "Knows contraceptive method"
label variable mv304_18 "Knows contraceptive method"
label variable mv304_19 "Knows contraceptive method"
label variable mv304_20 "Knows contraceptive method"
label variable mv305_01 "NA - Ever used contraceptive method"
label variable mv305_02 "NA - Ever used contraceptive method"
label variable mv305_03 "NA - Ever used contraceptive method"
label variable mv305_04 "NA - Ever used contraceptive method"
label variable mv305_05 "NA - Ever used contraceptive method"
label variable mv305_06 "NA - Ever used contraceptive method"
label variable mv305_07 "NA - Ever used contraceptive method"
label variable mv305_08 "NA - Ever used contraceptive method"
label variable mv305_09 "NA - Ever used contraceptive method"
label variable mv305_10 "NA - Ever used contraceptive method"
label variable mv305_11 "NA - Ever used contraceptive method"
label variable mv305_12 "NA - Ever used contraceptive method"
label variable mv305_13 "NA - Ever used contraceptive method"
label variable mv305_14 "NA - Ever used contraceptive method"
label variable mv305_15 "NA - Ever used contraceptive method"
label variable mv305_16 "NA - Ever used contraceptive method"
label variable mv305_17 "NA - Ever used contraceptive method"
label variable mv305_18 "NA - Ever used contraceptive method"
label variable mv305_19 "NA - Ever used contraceptive method"
label variable mv305_20 "NA - Ever used contraceptive method"
label variable mv307_01 "Contraceptive method currently used"
label variable mv307_02 "Contraceptive method currently used"
label variable mv307_03 "Contraceptive method currently used"
label variable mv307_04 "Contraceptive method currently used"
label variable mv307_05 "Contraceptive method currently used"
label variable mv307_06 "Contraceptive method currently used"
label variable mv307_07 "Contraceptive method currently used"
label variable mv307_08 "Contraceptive method currently used"
label variable mv307_09 "Contraceptive method currently used"
label variable mv307_10 "Contraceptive method currently used"
label variable mv307_11 "Contraceptive method currently used"
label variable mv307_12 "Contraceptive method currently used"
label variable mv307_13 "Contraceptive method currently used"
label variable mv307_14 "Contraceptive method currently used"
label variable mv307_15 "Contraceptive method currently used"
label variable mv307_16 "Contraceptive method currently used"
label variable mv307_17 "Contraceptive method currently used"
label variable mv307_18 "Contraceptive method currently used"
label variable mv307_19 "Contraceptive method currently used"
label variable mv307_20 "Contraceptive method currently used"
label variable mv312    "Current contraceptive method"
label variable mv313    "Current contraceptive by method type"
label variable mv323a   "Brand of condom used"
label variable mv325b   "NA - Cost of condoms last time obtained"
label variable mv372a   "NA - Interviewer shown condom package"
label variable mv384a   "On radio heard about Family Planning in the last few months"
label variable mv384b   "On TV saw about Family Planning in the last few months"
label variable mv384c   "In newspaper read about Family Planning in the last few months"
label variable mv395    "Discussed Family Planning with health worker in last few months"
label variable mv396    "NA - Possible for a breastfeeding woman to get pregnant"
label variable mv3a09b  "NA - Number of condoms did get last time"
label variable mv3b17   "Source of condoms"
label variable mv3b25a  "Contraception is woman's business, man should not worry"
label variable mv3b25b  "Women who use contraception become promiscuous"
label variable mv463a   "Smokes cigarettes"
label variable mv463b   "Smokes pipe"
label variable mv463c   "Uses chewing tobacco"
label variable mv463d   "Uses snuff"
label variable mv463e   "NA - Smokes CS"
label variable mv463f   "NA - Smokes CS"
label variable mv463g   "NA - Smokes CS"
label variable mv463x   "Smokes other"
label variable mv463z   "Smokes nothing"
label variable mv464    "Number of cigarettes in last 24 hours"
label variable mv474    "Heard of tuberculosis or TB"
label variable mv474a   "Tuberculosis spread by: air through coughing or sneezing"
label variable mv474b   "Tuberculosis spread by: sharing utensils"
label variable mv474c   "Tuberculosis spread by: touching a person with TB"
label variable mv474d   "Tuberculosis spread by: food"
label variable mv474e   "Tuberculosis spread by: sexual contact"
label variable mv474f   "Tuberculosis spread by: mosquito bites"
label variable mv474g   "NA - Tuberculosis spread by: CS"
label variable mv474h   "NA - Tuberculosis spread by: CS"
label variable mv474i   "NA - Tuberculosis spread by: CS"
label variable mv474j   "NA - Tuberculosis spread by: CS"
label variable mv474x   "Tuberculosis spread by: other"
label variable mv474z   "Don't know how tuberculosis is spread"
label variable mv475    "Tuberculosis can be cured"
label variable mv476    "Would want tuberculosis infection in family to remain secret"
label variable mv477    "Number of injections in last 12 months"
label variable mv478    "Number of injections administered by a health worker"
label variable mv479    "NA - Place where given injection by health worker"
label variable mv480    "Syringe and needle from new, unopened package"
label variable mv481    "Covered by health insurance"
label variable mv481a   "Health insurance type: mutual/community organization"
label variable mv481b   "Health insurance type: provided by employer"
label variable mv481c   "NA - Health insurance type: social security"
label variable mv481d   "Health insurance type: private/commercially purchased"
label variable mv481e   "Health insurance type: national/district health insurance(NHIS)"
label variable mv481f   "NA - Health insurance type: CS"
label variable mv481g   "NA - Health insurance type: CS"
label variable mv481h   "NA - Health insurance type: CS"
label variable mv481x   "Health insurance type: other"
label variable mv482a   "NA - Arrange care of biological children under age 18"
label variable mv482b   "NA - Primary caregiver of children under age 18"
label variable mv482c   "NA - Arrange care of non-biological children < 18"
label variable mv483    "Respondent circumcised"
label variable mv483a   "Age at circumcision"
label variable mv483b   "Who performed the circumcision"
label variable mv483c   "Place where circumcision was done"
label variable mv501    "Current marital status"
label variable mv502    "Currently/formerly/never in union"
label variable mv503    "Number of unions"
label variable mv504    "Currently residing with wife/partner"
label variable mv505    "Number of wives/partners"
label variable mv507    "Month of first cohabitation"
label variable mv508    "Year of first cohabitation"
label variable mv509    "Date of first cohabitation (CMC)"
label variable mv510    "Completeness of date information in MV509"
label variable mv511    "Age at first cohabitation"
label variable mv512    "Years since first cohabitation"
label variable mv513    "Cohabitation duration (grouped)"
label variable mv525    "Age at first sex"
label variable mv527    "Time since last sex"
label variable mv528    "Time since last sex (in days)"
label variable mv529    "Time since last sex (in months)"
label variable mv531    "Age at first sex (imputed)"
label variable mv532    "Flag for MV531"
label variable mv535    "Ever been married or in union"
label variable mv536    "Recent sexual activity"
label variable mv541    "NA - Intends to wait until marriage to have sex"
label variable mv602    "Fertility preference"
label variable mv603    "Preferred waiting time for birth of a/another child"
label variable mv604    "Preferred waiting time for birth of a/another child (grouped)"
label variable mv605    "Desire for more children"
label variable mv613    "Ideal number of children"
label variable mv614    "Ideal number of children (grouped)"
label variable mv616    "Desired time for future birth"
label variable mv621    "NA - Wife's desire for children"
label variable mv627    "Ideal number of boys"
label variable mv628    "Ideal number of girls"
label variable mv629    "Ideal number of either sex"
label variable mv631    "NA - Problem if wife became pregnant"
label variable mv633a   "NA - Wife justified refusing sex: husband has STI"
label variable mv633b   "Wife justified refusing sex: husband has other women"
label variable mv633c   "NA - Wife justified refusing sex: recent birth"
label variable mv633d   "NA - Wife justified refusing sex: tired, not in mood"
label variable mv633e   "NA - Wife justified refusing sex: CS reason"
label variable mv633f   "NA - Wife justified refusing sex: CS reason"
label variable mv633g   "NA - Wife justified refusing sex: CS reason"
label variable mv634a   "NA - Wife refuses to have sex, husband has right to: get angry"
label variable mv634b   "NA - Wife refuses to have sex, husband has right to: refuse financial support"
label variable mv634c   "NA - Wife refuses to have sex, husband has right to: use force for sex"
label variable mv634d   "NA - Wife refuses to have sex, husband has right to: have sex with another women"
label variable mv714    "Currently working"
label variable mv714a   "Have a job, but currently absent"
label variable mv716    "Occupation"
label variable mv717    "Occupation (grouped)"
label variable mv719    "NA - Works for family, others, self"
label variable mv721    "NA - Works at home or away"
label variable mv731    "Worked in last 12 months"
label variable mv732    "Employment all year/seasonal"
label variable mv739    "Person who usually decides how to spend respondent's earnings"
label variable mv740    "NA - Type of land where respondent works"
label variable mv741    "Type of earnings from respondent's work"
label variable mv743a   "Person who should have greater say: respondent's health care"
label variable mv743b   "Person who should have greater say: large household purchases"
label variable mv743c   "NA - Person who should have greater say: daily household purchases"
label variable mv743d   "NA - Person who should have greater say: visits to family or relatives"
label variable mv743e   "NA - Person who should have greater say: food to be cooked each day"
label variable mv743f   "NA - Person who should have greater say: deciding what to do with money wife ear"
label variable mv743g   "NA - Person who should have greater say: deciding how many children to have"
label variable mv744a   "Beating justified: wife goes out without telling husband"
label variable mv744b   "Beating justified: wife neglects the children"
label variable mv744c   "Beating justified: wife argues with husband"
label variable mv744d   "Beating justified: wife refuses to have sex with husband"
label variable mv744e   "Beating justified: wife burns food"
label variable mv745a   "Owns a house alone or jointly"
label variable mv745b   "Owns land alone or jointly"
label variable mv747a   "NA - Childbearing is a woman's concern"
label variable mv747b   "NA - Important for mother/child health to get assistance at delivery"
label variable mv750    "Ever heard of a Sexually Transmitted Infection (STI)"
label variable mv751    "Ever heard of AIDS"
label variable mv754bp  "NA - Reduce risk of getting HIV: do not have sex at all"
label variable mv754cp  "Reduce risk of getting HIV: always use condoms during sex"
label variable mv754dp  "Reduce risk of getting HIV: have 1 sex partner only, who has no other partners"
label variable mv754jp  "Can get HIV from mosquito bites"
label variable mv754wp  "Can get HIV by sharing food with person who has AIDS"
label variable mv756    "A healthy looking person can have HIV"
label variable mv761    "Condom used during last sex with most recent partner"
label variable mv761b   "Condom used during last sex with 2nd to most recent partner"
label variable mv761c   "Condom used during last sex with 3rd to most recent partner"
label variable mv762aa  "Source for condoms: government hospital/polyclinic"
label variable mv762ab  "Source for condoms: government health center"
label variable mv762ac  "Source for condoms: government health post/CHPS"
label variable mv762ad  "Source for condoms: family planning clinic"
label variable mv762ae  "Source for condoms: mobile clinic"
label variable mv762af  "Source for condoms: fieldworker/outreach/peer educator"
label variable mv762ag  "NA - Source for condoms: CS public"
label variable mv762ah  "NA - Source for condoms: CS public"
label variable mv762ai  "Source for condoms: other public"
label variable mv762aj  "Source for condoms: private hospital/clinic"
label variable mv762ak  "Source for condoms: pharmacy"
label variable mv762al  "Source for condoms: private doctor"
label variable mv762am  "Source for condoms: chemical/drug store"
label variable mv762an  "Source for condoms: FP/PPAG clinic"
label variable mv762ao  "Source for condoms: maternity home"
label variable mv762ap  "NA - Source for condoms: CS private"
label variable mv762aq  "NA - Source for condoms: CS private"
label variable mv762ar  "Source for condoms: other private"
label variable mv762as  "Source for condoms: shop/market"
label variable mv762at  "Source for condoms: church"
label variable mv762au  "Source for condoms: community volunteer"
label variable mv762av  "Source for condoms: friend/relative"
label variable mv762aw  "NA - Source for condoms: CS other"
label variable mv762ax  "Source for condoms: other"
label variable mv762az  "Don't know any source for condoms"
label variable mv762ba  "Source for female condoms: government hospital/polyclinic"
label variable mv762bb  "Source for female condoms: government health center"
label variable mv762bc  "Source for female condoms: government health post/CHPS"
label variable mv762bd  "Source for female condoms: family planning clinic"
label variable mv762be  "Source for female condoms: mobile clinic"
label variable mv762bf  "Source for female condoms: fieldworker/outreach/peer educator"
label variable mv762bg  "NA - Source for female condoms: CS public"
label variable mv762bh  "NA - Source for female condoms: CS public"
label variable mv762bi  "Source for female condoms: other public"
label variable mv762bj  "Source for female condoms: private hospital/clinic"
label variable mv762bk  "Source for female condoms: pharmacy"
label variable mv762bl  "Source for female condoms: private doctor"
label variable mv762bm  "Source for female condoms: chemical/drug store"
label variable mv762bn  "Source for female condoms: FP/FFAG clinic"
label variable mv762bo  "Source for female condoms: maternity home"
label variable mv762bp  "NA - Source for female condoms: CS private"
label variable mv762bq  "NA - Source for female condoms: CS private"
label variable mv762br  "Source for female condoms: other private"
label variable mv762bs  "Source for female condoms: shop/market"
label variable mv762bt  "Source for female condoms: church"
label variable mv762bu  "Source for female condoms: community volunteer"
label variable mv762bv  "Source for female condoms: friend/relative"
label variable mv762bw  "NA - Source for female condoms: CS other"
label variable mv762bx  "Source for female condoms: other"
label variable mv762bz  "Don't know any source for female condoms"
label variable mv763a   "Had any STI in last 12 months"
label variable mv763b   "Had genital sore/ulcer in last 12 months"
label variable mv763c   "Had genital discharge in last 12 months"
label variable mv763d   "NA - Had CS STI in last 12 months"
label variable mv763e   "NA - Had CS STI in last 12 months"
label variable mv763f   "NA - Had CS STI in last 12 months"
label variable mv763g   "NA - Had CS STI in last 12 months"
label variable mv766a   "Number of sex partners, excluding spouse, in last 12 months"
label variable mv766b   "Number of sex partners, including spouse, in last 12 months"
label variable mv767a   "Relationship with most recent sex partner"
label variable mv767b   "Relationship with 2nd to most recent sex partner"
label variable mv767c   "Relationship with 3rd to most recent sex partner"
label variable mv768a   "NA - Length of time had sex relations with most recent partner"
label variable mv768b   "NA - Length of time had sex relations with 2nd to most recent partner"
label variable mv768c   "NA - Length of time had sex relations with 3rd to most recent partner"
label variable mv769    "Can get a condom"
label variable mv769a   "Can get a female condom"
label variable mv770    "Sought advice/treatment for last STI infection"
label variable mv770a   "Sought STI advice/treatment from: government hospital"
label variable mv770b   "Sought STI advice/treatment from: government health center"
label variable mv770c   "Sought STI advice/treatment from: government health post/CHPS"
label variable mv770d   "Sought STI advice/treatment from: stand-alone VCT center"
label variable mv770e   "Sought STI advice/treatment from: family planning clinic"
label variable mv770f   "Sought STI advice/treatment from: mobile clinic"
label variable mv770g   "Sought STI advice/treatment from: fieldworker/outreach/peer educator"
label variable mv770h   "NA - Sought STI advice/treatment from: CS public"
label variable mv770i   "NA - Sought STI advice/treatment from: CS public"
label variable mv770j   "Sought STI advice/treatment from: other public"
label variable mv770k   "Sought STI advice/treatment from: private hospital/clinic/doctor"
label variable mv770l   "Sought STI advice/treatment from: stand-alone VCT center"
label variable mv770m   "Sought STI advice/treatment from: pharmacy"
label variable mv770n   "Sought STI advice/treatment from: chemical/drug store"
label variable mv770o   "Sought STI advice/treatment from: FP/PPAG clinic"
label variable mv770p   "Sought STI advice/treatment from: maternity home"
label variable mv770q   "NA - Sought STI advice/treatment from: CS private"
label variable mv770r   "NA - Sought STI advice/treatment from: CS private"
label variable mv770s   "Sought STI advice/treatment from: other private"
label variable mv770t   "Sought STI advice/treatment from: home"
label variable mv770u   "Sought STI advice/treatment from: correctional facility"
label variable mv770v   "NA - Sought STI advice/treatment from: CS other"
label variable mv770w   "NA - Sought STI advice/treatment from: CS other"
label variable mv770x   "Sought STI advice/treatment from: other"
label variable mv774a   "HIV transmitted during pregnancy"
label variable mv774b   "HIV transmitted during delivery"
label variable mv774c   "HIV transmitted by breastfeeding"
label variable mv775    "NA - Knows someone who has, or is suspected of having, HIV"
label variable mv777    "Would want HIV infection in family to remain secret"
label variable mv778    "Willing to care for relative with AIDS"
label variable mv779    "A female teacher infected with HIV, but is not sick, should be allowed to contin"
label variable mv780    "Children should be taught about condoms to avoid AIDS"
label variable mv781    "Ever been tested for HIV"
label variable mv783    "Know a place to get HIV test"
label variable mv784a   "Place for HIV test: government hospital/polyclinic"
label variable mv784b   "Place for HIV test: government health center"
label variable mv784c   "Place for HIV test: government post/CHPS"
label variable mv784d   "Place for HIV test: stand-alone VCT center"
label variable mv784e   "Place for HIV test: family planning clinic"
label variable mv784f   "Place for HIV test: mobile clinic"
label variable mv784g   "Place for HIV test: fieldworker/outreach/peer educator"
label variable mv784h   "NA - Place for HIV test: CS public"
label variable mv784i   "NA - Place for HIV test: CS public"
label variable mv784j   "Place for HIV test: other public"
label variable mv784k   "Place for HIV test: private hospital/clinic/doctor"
label variable mv784l   "Place for HIV test: stand-alone VCT center"
label variable mv784m   "Place for HIV test: pharmacy"
label variable mv784n   "Place for HIV test: chemical/drug store"
label variable mv784o   "Place for HIV test: FP/PPAG clinic"
label variable mv784p   "Place for HIV test: maternity home"
label variable mv784q   "NA - Place for HIV test: CS private"
label variable mv784r   "Place for HIV test: other private"
label variable mv784s   "Place for HIV test: home"
label variable mv784t   "Place for HIV test: correctional facility"
label variable mv784u   "NA - Place for HIV test: CS other"
label variable mv784v   "NA - Place for HIV test: CS other"
label variable mv784x   "Place for HIV test: other"
label variable mv785    "Heard about other STIs"
label variable mv791    "Have ever paid anyone in exchange for sex"
label variable mv793    "Paid for sex in last 12 months"
label variable mv793a   "Condom used last time paid for sex in last 12 months"
label variable mv793b   "Condom used every time paid for sex in last 12 months"
label variable mv820    "NA - Condom used at first sex"
label variable mv822    "Wife justified asking husband to use condom if he has STI"
label variable mv823    "Can get HIV by witchcraft or supernatural means"
label variable mv824    "Drugs to avoid HIV transmission to baby during pregnancy"
label variable mv825    "Would buy vegetables from vendor with HIV"
label variable mv826    "NA - Last time tested for HIV"
label variable mv826a   "Months ago most recent HIV test"
label variable mv827    "NA - Last HIV test: on your own, offered or required"
label variable mv828    "Received result from last HIV test"
label variable mv829    "Place where last HIV test was taken"
label variable mv832b   "Time since last sex with 2nd to most recent partner"
label variable mv832c   "Time since last sex with 3rd to most recent partner"
label variable mv833a   "Used condom every time had sex with most recent partner in last 12 months"
label variable mv833b   "Used condom every time had sex with 2nd to most recent partner in last 12 months"
label variable mv833c   "Used condom every time had sex with 3rd to most recent partner in last 12 months"
label variable mv834a   "Age of most recent partner"
label variable mv834b   "Age of 2nd to most recent partner"
label variable mv834c   "Age of 3rd to most recent partner"
label variable mv835a   "NA - Alcohol consumption at last sex with most recent partner"
label variable mv835b   "NA - Alcohol consumption at last sex with 2nd to most recent partner"
label variable mv835c   "NA - Alcohol consumption at last sex with 3rd to most recent partner"
label variable mv836    "Total lifetime number of sex partners"
label variable mv837    "NA - Heard of drugs to help HIV infected people live longer"
label variable mv844    "NA - Knows someone denied health services for having, or suspected of having, HI"
label variable mv845    "NA - Knows someone denied social event for having, or suspected of having, HIV; "
label variable mv846    "NA - Knows someone verbally abused for having, or suspected of having, HIV; in l"
label variable mv847    "NA - People with HIV should be ashamed of themselves"
label variable mv848    "NA - People with HIV should be blamed for bringing disease to community"
label variable mv849    "NA - Children 12-14 should be taught to wait for sex until marriage"
label variable mv851a   "NA - Young men should wait for sex until marriage"
label variable mv851b   "NA - Most young men wait for sex until marriage"
label variable mv851c   "NA - Unmarried sexually active men should have only one partner"
label variable mv851d   "NA - Most unmarried sexually active men have only one partner"
label variable mv851e   "NA - Married men should only have sex with their wives"
label variable mv851f   "NA - Most married men only have sex with their wives"
label variable mv851g   "NA - Young women should wait for sex until marriage"
label variable mv851h   "NA - Most young women wait for sex until marriage"
label variable mv851i   "NA - Unmarried sexually active women should have only one partner"
label variable mv851j   "NA - Most unmarried sexually active women have only one partner"
label variable mv851k   "NA - Married women should only have sex with their husbands"
label variable mv851l   "NA - Most married women only have sex with their husbands"
label variable mv852a   "How long ago first had sex with most recent partner"
label variable mv852b   "How long ago first had sex with 2nd most recent partner"
label variable mv852c   "How long ago first had sex with 3rd most recent partner"
label variable mv853a   "Times in last 12 months had sex with most recent partner"
label variable mv853b   "Times in last 12 months had sex with 2nd most recent partner"
label variable mv853c   "Times in last 12 months had sex with 3rd most recent partner"
label variable mv854a   "Concurrent sexual partners"
label variable mv854b   "Cumulative concurrent sexual partners"
label variable smdist   "District"
label variable smlanq   "Language of questionnaires"
label variable smlani   "Language of interview"
label variable smlanr   "Language of respondent"
label variable smtrans  "Translator used"
label variable sm101a   "Agree on blood pressure measurement"
label variable sm101b1  "Eaten in the past 10 minutes"
label variable sm101b2  "Had coffeine in the past 10 minutes"
label variable sm101b3  "Smoked in the past 10 minutes"
label variable sm101b4  "Exercised in the past 10 minutes"
label variable sm101c   "Arm circumference"
label variable sm101d   "Blood pressure monitor model and cuff size"
label variable sm101e1  "1st measurement: Systolic"
label variable sm101e2  "1st measurement: Diastolic"
label variable sm101e3  "Reason not measured"
label variable sm105    "Highest educational level"
label variable sm106    "Highest grade/form/year at that level"
label variable smeduc   "Educational level as in final report"
label variable sm106b   "Age of being enrolled in primary school"
label variable sm106c   "Current school attendance"
label variable sm106d   "Reason for stopping school attendance"
label variable sm401a   "Bridewealth in the current union"
label variable sm401b1  "Why was the bridewealth not negotiated: family didn't agree"
label variable sm401b2  "Why was the bridewealth not negotiated: bridewealth not negotiable"
label variable sm401b3  "Why was the bridewealth not negotiated: husband not given opportunity to negotia"
label variable sm401b4  "Why was the bridewealth not negotiated: family ties"
label variable sm401b5  "Why was the bridewealth not negotiated: I didn't agree"
label variable sm401b6  "Why was the bridewealth not negotiated: no need"
label variable sm401b7  "Why was the bridewealth not negotiated: prestige"
label variable sm401b8  "Why was the bridewealth not negotiated: detected wife was pregnant"
label variable sm401b9  "Why was the bridewealth not negotiated: other"
label variable sm401c   "Status of the bridewealth"
label variable sm401d1  "Why bridewealth was not paid completely: it was expensive"
label variable sm401d2  "Why bridewealth was not paid completely: agreed to pay in installments"
label variable sm401d3  "Why bridewealth was not paid completely: intentionally"
label variable sm401d4  "Why bridewealth was not paid completely: detected wife was pregnant"
label variable sm401d5  "Why bridewealth was not paid completely: financial constraint"
label variable sm401d6  "Why bridewealth was not paid completely: part of bridewealth used for other purp"
label variable sm401d7  "Why bridewealth was not paid completely: family ties"
label variable sm401d8  "Why bridewealth was not paid completely: customary demands"
label variable sm401d9  "Why bridewealth was not paid completely: other"
label variable sm500a   "Time of measurement (hhmm - 24 hour clock)"
label variable sm500b   "Agree on blood pressure measurement"
label variable sm500c1  "2nd measurement: Systolic"
label variable sm500c2  "2nd measurement: Diastolic"
label variable sm500c3  "Reason not measured"
label variable sm710a   "Have heard about antiretroviral drugs"
label variable sm812a   "Registered with NHIS"
label variable sm814a   "Insurance covers antenatal health care"
label variable sm814b   "Insurance covers childbirth"
label variable sm814c   "Insurance covers PNC mother"
label variable sm814d   "Insurance covers PNC child"
label variable sm814e   "Insurance covers cash benefits"
label variable sm814f   "Insurance covers other"
label variable sm816a   "Why not registered with NHIS: not heard of this"
label variable sm816b   "Why not registered with NHIS: cannot afford premium"
label variable sm816c   "Why not registered with NHIS: don't trust"
label variable sm816d   "Why not registered with NHIS: don't need health insurance"
label variable sm816e   "Why not registered with NHIS: NHIS doesn't cover health service I need"
label variable sm816f   "Why not registered with NHIS: don't understands scheme"
label variable sm816g   "Why not registered with NHIS: don't know where to register"
label variable sm816h   "Why not registered with NHIS: no easy access to a health facility"
label variable sm816i   "Why not registered with NHIS: don't like the attitude of staff in a health facil"
label variable sm816j   "Why not registered with NHIS: those with insurance are given substandard service"
label variable sm816x   "Why not registered with NHIS: other"
label variable sm817    "Pay NHIS membership"
label variable sm818    "Hold a valid NHIS card"
label variable sm819    "Why does not have a valid NHIS card"
label variable sm820    "Number of weeks it took to issue a NHIS card"
label variable sm821    "Plan to renew NHIS card"
label variable sm822a   "Why not want to renew NHIS card: have not been sick"
label variable sm822b   "Why not want to renew NHIS card: premium expensive"
label variable sm822c   "Why not want to renew NHIS card: still pay out of pocket"
label variable sm822d   "Why not want to renew NHIS card: poor quality care with card"
label variable sm822e   "Why not want to renew NHIS card: waiting time for card long"
label variable sm822f   "Why not want to renew NHIS card: used services not covered"
label variable sm822g   "Why not want to renew NHIS card: didn't use any health services"
label variable sm822h   "Why not want to renew NHIS card: use clinics or traditional practitioners who ar"
label variable sm822x   "Why not want to renew NHIS card: other"
label variable sm823    "Pay out of pocket for durgs and services"
label variable sm824    "Whether service not covered by NHIS"
label variable sm825a   "Service not covered: family planning"
label variable sm825b   "Service not covered: laboratory investigations"
label variable sm825c   "Service not covered: antenatal care"
label variable sm825d   "Service not covered: postnatal care"
label variable sm825e   "Service not covered: care for newborn for up to 3 months"
label variable sm825x   "Service not covered: other"
label variable sm826    "Quality of service by holding NHIS card"
label variable sm827    "Receive good service last time"
label variable sm828    "Program helping pregnant women accessing health services"
label variable sm829a   "Program helping women accessing health services: free NHIS premium for pregnant "
label variable sm829x   "Program helping women accessing health services: other"
label variable sm830    "Program helping children under 18 accessing health services"
label variable sm831a   "Program helping children under 18 accessing health services: free NHIS premium f"
label variable sm831x   "Program helping children under 18 accessing health services: other"
label variable sm836    "Ever been told as having hypertension or high blood pressure"
label variable sm837    "Was told on 2+ occasions that respondent has hypertension"
label variable sm838a   "To lower blood pressure, take medicine"
label variable sm838b   "To lower blood pressure, control weight"
label variable sm838c   "To lower blood pressure, cut down salt"
label variable sm838d   "To lower blood pressure, exercise"
label variable sm838e   "To lower blood pressure, cut down alcohol"
label variable sm838f   "To lower blood pressure, stop smoking"
label variable sm839    "Ever heard about iodized salt"
label variable sm840a   "Benefits for consuming iodized salt: improve intelligence"
label variable sm840b   "Benefits for consuming iodized salt: provides energy"
label variable sm840c   "Benefits for consuming iodized salt: prevents still birth"
label variable sm840d   "Benefits for consuming iodized salt: prevents mental detardation"
label variable sm840e   "Benefits for consuming iodized salt: prevents miscarriages"
label variable sm840f   "Benefits for consuming iodized salt: prevents goiter"
label variable sm840x   "Benefits for consuming iodized salt: other"
label variable sm840z   "Benefits for consuming iodized salt: don't know"
label variable sm841a   "How to tell iodized salt from non-iodized salt: testing salt"
label variable sm841b   "How to tell iodized salt from non-iodized salt: iodized salt logo"
label variable sm841c   "How to tell iodized salt from non-iodized salt: fine powered salt"
label variable sm841x   "How to tell iodized salt from non-iodized salt: other"
label variable sm841z   "How to tell iodized salt from non-iodized salt: don't know"
label variable sm842    "Days ate fruits in the past 7 days"
label variable sm844    "Days ate vegetables in the past 7 days"
label variable sm846    "Visited a health facility in the last 6 months"
label variable sm847    "Type of facility visited most recently"
label variable sm848    "Service received most recently"
label variable sm849    "How to pay the most recent service"
label variable sm850    "The easiness of getting care"
label variable sm851    "Convenience location health facility"
label variable sm852    "How good are the opening hours during the day"
label variable sm853a   "Satisfaction of the time to wait for your turn"
label variable sm853b   "Satisfaction of the time spent in consulting/examination room"
label variable sm853c   "Satisfaction of the time to wait for tests to be performed"
label variable sm853d   "Satisfaction of the time to wait for test results"
label variable sm853e   "Satisfaction of the time at pharmacy/dispensary"
label variable sm854a   "Satisfaction of staff when they listened to the respondent"
label variable sm854b   "Satisfaction of staff when they explained what was wanted"
label variable sm854c   "Satisfaction of staff when they gave advice on treatment"
label variable sm855    "Health provider spent enough time with the respondent"
label variable sm856    "Health provider sought consent before treatment"
label variable sm857    "Health provider friendly to the respondent"
label variable sm858a   "Satisfaction of the cleanliness of the facility"
label variable sm858b   "Satisfaction of the easiness of finding where to go"
label variable sm858c   "Satisfaction of comfort and safety while waiting"
label variable sm858d   "Satisfaction of privacy during the examination"
label variable sm858e   "Satisfaction of confidentiality and protection of personal information"
label variable sm860    "Time of measurement (hhmm - 24 hour clock)"
label variable sm861    "Agree on blood pressure measurement"
label variable sm862a   "3rd measurement: Systolic"
label variable sm862b   "3rd measurement: Diastolic"
label variable sm862c   "Reason not measured"

#delimit ;
label define MV013   
     1 "15-19"
     2 "20-24"
     3 "25-29"
     4 "30-34"
     5 "35-39"
     6 "40-44"
     7 "45-49"
     8 "50-54"
     9 "55-59"
    10 "60-64"
;
label define MV014   
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     4 "Year and age - year ignored"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define MV015   
     1 "Completed"
     2 "Not at home"
     3 "Postponed"
     4 "Refused"
     5 "Partly completed"
     6 "Incapacitated"
     7 "Other"
;
label define MV022   
     1 "Western Urban"
     2 "Western Rural"
     3 "Central Urban"
     4 "Central Rural"
     5 "Greater Accra Urban"
     6 "Greater Accra Rural"
     7 "Volta Urban"
     8 "Volta Rural"
     9 "Eastern Urban"
    10 "Eastern Rural"
    11 "Ashanti Urban"
    12 "Ashanti Rural"
    13 "Brong Ahafo Urban"
    14 "Brong Ahafo Rural"
    15 "Northern Urban"
    16 "Northern Rural"
    17 "Upper East Urban"
    18 "Upper East Rural"
    19 "Upper West Urban"
    20 "Upper West Rural"
;
label define MV023   
     1 "Western Urban"
     2 "Western Rural"
     3 "Central Urban"
     4 "Central Rural"
     5 "Greater Accra Urban"
     6 "Greater Accra Rural"
     7 "Volta Urban"
     8 "Volta Rural"
     9 "Eastern Urban"
    10 "Eastern Rural"
    11 "Ashanti Urban"
    12 "Ashanti Rural"
    13 "Brong Ahafo Urban"
    14 "Brong Ahafo Rural"
    15 "Northern Urban"
    16 "Northern Rural"
    17 "Upper East Urban"
    18 "Upper East Rural"
    19 "Upper West Urban"
    20 "Upper West Rural"
;
label define MV024   
     1 "Western"
     2 "Central"
     3 "Greater Accra"
     4 "Volta"
     5 "Eastern"
     6 "Ashanti"
     7 "Brong Ahafo"
     8 "Northern"
     9 "Upper East"
    10 "Upper West"
;
label define MV025   
     1 "Urban"
     2 "Rural"
;
label define MV026   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define MV027   
     9 "Missing"
;
label define MV028   
   999 "Missing"
;
label define MV029   
    99 "Missing"
;
label define MV030   
   999 "Missing"
;
label define MV031   
   999 "Missing"
;
label define MV032   
    99 "Missing"
;
label define MV034   
     0 "Wife not in household"
;
label define MV034A  
     1 "Wife"
     2 "Partner"
;
label define MV034B  
    99 "Missing"
;
label define MV035   
     0 "No wives/partners"
;
label define MV801   
  9999 "Missing"
;
label define MV802   
  9999 "Missing"
;
label define MV803   
    95 "95+"
    96 "2+ visits"
    97 "Inconsistent"
;
label define MV101   
     1 "Western"
     2 "Central"
     3 "Greater Accra"
     4 "Volta"
     5 "Eastern"
     6 "Ashanti"
     7 "Brong Ahafo"
     8 "Northern"
     9 "Upper East"
    10 "Upper West"
;
label define MV102   
     1 "Urban"
     2 "Rural"
;
label define MV103   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define MV104   
    95 "Always"
    96 "Visitor"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV105   
     0 "Capital, large city"
     1 "City"
     2 "Town"
     3 "Countryside"
     4 "Abroad"
;
label define MV106   
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define MV107   
     0 "No years completed at level MV106"
;
label define MV130   
     1 "Catholic"
     2 "Anglican"
     3 "Methodist"
     4 "Presbyterian"
     5 "Pentecostal/charismatic"
     6 "Other Christian"
     7 "Islam"
     8 "Traditional/spiritualist"
     9 "No religion"
    96 "Other"
;
label define MV131   
     1 "Akan"
     2 "Ga/Dangme"
     3 "Ewe"
     4 "Guan"
     5 "Mole-Dagbani"
     6 "Grusi"
     7 "Gurma"
     8 "Mande"
   996 "Other"
;
label define MV133   
    97 "Inconsistent"
;
label define MV134   
     0 "Capital, large city"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define MV135   
     1 "Usual resident"
     2 "Visitor"
;
label define MV149   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
;
label define MV150   
     1 "Head"
     2 "Husband"
     3 "Son"
     4 "Son-in-law"
     5 "Grandson"
     6 "Father"
     7 "Father-in-law"
     8 "Brother"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "Don't know"
;
label define MV151   
     1 "Male"
     2 "Female"
;
label define MV152   
    97 "97+"
    98 "Don't know"
;
label define MV155   
     0 "Cannot read at all"
     1 "Able to read only parts of sentence"
     2 "Able to read whole sentence"
     3 "No card with required language"
     4 "Blind/visually impaired"
;
label define MV156   
     0 "No"
     1 "Yes"
;
label define MV157   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV158   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV159   
     0 "Not at all"
     1 "Less than once a week"
     2 "At least once a week"
     3 "Almost every day"
;
label define MV167   
     0 "None"
    90 "90+"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV168   
     0 "No"
     1 "Yes"
;
label define MV190   
     1 "Poorest"
     2 "Poorer"
     3 "Middle"
     4 "Richer"
     5 "Richest"
;
label define MV212   
    99 "Missing"
;
label define MV213   
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV217   
     1 "During her period"
     2 "After period ended"
     3 "Middle of the cycle"
     4 "Before period begins"
     5 "At any time"
     6 "Other"
     8 "Don't know"
;
label define MV225   
     1 "Then"
     2 "Later"
     3 "Not at all"
;
label define MV245   
    99 "Missing"
;
label define MV246   
     0 "No"
     1 "Yes"
;
label define MV247   
    99 "Missing"
;
label define MV248   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV249   
     0 "Not present"
     1 "Present"
;
label define MV250   
     1 "Hospital, health facility"
     2 "Other"
;
label define MV251   
     1 "Costs too much"
     2 "Facility not open"
     3 "Too far/no transportation"
     4 "Don't trust facility/poor quality service"
     5 "No female provider at facility"
     6 "Not the first child"
     7 "Child's mother did not think it was necessary"
     8 "He did not think it was necessary"
     9 "Family did not think necessary"
    10 "Family/husband did not allow"
    11 "Not customary"
    12 "S/He did not know where to go"
    13 "He could not accompany her"
    14 "Inconventient service hour"
    15 "Long waiting time"
    96 "Other"
    98 "Don't know"
;
label define MV252   
     0 "Nothing to drink"
     2 "Less than usual/much less"
     3 "Somewhat less"
     4 "About the same"
     5 "More"
     8 "Don't know"
;
label define MV301   
     0 "Knows no method"
     1 "Knows only folkloric method"
     2 "Knows only traditional method"
     3 "Knows modern method"
;
label define MV302   
     0 "Never used"
     1 "Used only folkloric method"
     2 "Used only traditional method"
     3 "Used modern method"
;
label define M304A   
     1 "Modern method"
     2 "Traditional method"
     3 "Folkloric method"
;
label define MV304   
     0 "No"
     1 "Yes"
     7 "Not in contraception table, but as a current method"
     8 "Not asked"
;
label define MV305   
     0 "No"
     1 "Yes"
;
label define MV307   
     0 "No"
     1 "Yes"
;
label define MV312   
     0 "Not using"
     1 "Pill"
     2 "IUD"
     3 "Injections"
     4 "Diaphragm"
     5 "Condom"
     6 "Female Sterilization"
     7 "Male Sterilization"
     8 "Periodic Abstinence"
     9 "Withdrawal"
    10 "Other"
    11 "Implants/Norplant"
    12 "Abstinence"
    13 "Lactational amenorrhea (LAM)"
    14 "Female condom"
    15 "Foam or jelly"
    17 "Other modern method"
    18 "Survey Specific method 2"
    19 "Survey Specific method 3"
    20 "Survey Specific method 4"
    98 "Don't know"
;
label define MV313   
     0 "No method"
     1 "Folkloric method"
     2 "Traditional method"
     3 "Modern method"
     8 "Don't know"
;
label define MV323A  
     1 "Champion"
     2 "Gold Cycle"
     3 "Panther"
     4 "Bazooka"
     5 "Be Safe, no logo"
    96 "Other"
    98 "Don't know"
;
label define MV325B  
9999995 "Free"
9999998 "Don't know"
;
label define MV372A  
     0 "Package not seen"
     1 "Package seen"
;
label define MV384A  
     0 "No"
     1 "Yes"
;
label define MV384B  
     0 "No"
     1 "Yes"
;
label define MV384C  
     0 "No"
     1 "Yes"
;
label define MV395   
     0 "No"
     1 "Yes"
     2 "Depends"
     8 "Don't know"
;
label define MV396   
     0 "No"
     1 "Yes"
     2 "Depends"
     8 "Don't know"
;
label define MV3A09B 
   998 "Don't know"
;
label define MV3B17  
    11 "Government hospital / polyclinic"
    12 "Government health center"
    13 "Government health post / CHPS"
    14 "FP clinic"
    15 "Mobile clinic"
    16 "Fieldworker / outreach / peer educator"
    17 "Other public"
    21 "Private hospital, clinic"
    22 "Private doctor"
    23 "Pharmacy"
    24 "Chemical / drug store"
    25 "FP / PPAG Clinic"
    26 "Maternity home"
    27 "Other private medical"
    31 "Shop / market"
    32 "Church"
    33 "Community volunteer"
    34 "Friends, relatives"
    96 "Other"
;
label define MV3B25A 
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV3B25B 
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV463A  
     0 "No"
     1 "Yes"
;
label define MV463B  
     0 "No"
     1 "Yes"
;
label define MV463C  
     0 "No"
     1 "Yes"
;
label define MV463D  
     0 "No"
     1 "Yes"
;
label define MV463E  
     0 "No"
     1 "Yes"
;
label define MV463F  
     0 "No"
     1 "Yes"
;
label define MV463G  
     0 "No"
     1 "Yes"
;
label define MV463X  
     0 "No"
     1 "Yes"
;
label define MV463Z  
     0 "No"
     1 "Yes, smokes nothing"
;
label define MV464   
    98 "Don't know"
;
label define MV474   
     0 "No"
     1 "Yes"
;
label define MV474A  
     0 "No"
     1 "Yes"
;
label define MV474B  
     0 "No"
     1 "Yes"
;
label define MV474C  
     0 "No"
     1 "Yes"
;
label define MV474D  
     0 "No"
     1 "Yes"
;
label define MV474E  
     0 "No"
     1 "Yes"
;
label define MV474F  
     0 "No"
     1 "Yes"
;
label define MV474G  
     0 "No"
     1 "Yes"
;
label define MV474H  
     0 "No"
     1 "Yes"
;
label define MV474I  
     0 "No"
     1 "Yes"
;
label define MV474J  
     0 "No"
     1 "Yes"
;
label define MV474X  
     0 "No"
     1 "Yes"
;
label define MV474Z  
     0 "No"
     1 "Yes"
;
label define MV475   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV476   
     0 "No"
     1 "Yes, remain a secret"
     8 "Don't know/not sure/depends"
;
label define MV477   
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define MV478   
     0 "None"
    90 "90+"
    98 "Don't know"
;
label define MV479   
    10 "PUBLIC SECTOR"
    20 "PRIVATE SECTOR"
    30 "OTHER"
    96 "Other"
;
label define MV480   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV481   
     0 "No"
     1 "Yes"
;
label define MV481A  
     0 "No"
     1 "Yes"
;
label define MV481B  
     0 "No"
     1 "Yes"
;
label define MV481C  
     0 "No"
     1 "Yes"
;
label define MV481D  
     0 "No"
     1 "Yes"
;
label define MV481E  
     0 "No"
     1 "Yes"
;
label define MV481F  
     0 "No"
     1 "Yes"
;
label define MV481G  
     0 "No"
     1 "Yes"
;
label define MV481H  
     0 "No"
     1 "Yes"
;
label define MV481X  
     0 "No"
     1 "Yes"
;
label define MV482A  
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV482B  
     0 "No"
     1 "Yes"
;
label define MV482C  
     0 "No"
     1 "Yes"
     8 "Unsure"
;
label define MV483   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV483A  
    95 "During childhood <5 years"
    98 "Don't know"
;
label define MV483B  
     1 "Traditional practitioner / family friend"
     2 "Health worker / professional"
    96 "Other"
    98 "Don't know"
;
label define MV483C  
     1 "Health facility"
     2 "Home of a health worker / professional"
     3 "Circumcision done at home"
     4 "Ritual site"
    96 "Other home / place"
    98 "Don't know"
;
label define MV501   
     0 "Never in union"
     1 "Married"
     2 "Living with partner"
     3 "Widowed"
     4 "Divorced"
     5 "No longer living together/separated"
;
label define MV502   
     0 "Never in union"
     1 "Currently in union/living with a woman"
     2 "Formerly in union/living with a woman"
;
label define MV503   
     1 "Once"
     2 "More than once"
;
label define MV504   
     1 "Living with him"
     2 "Staying elsewhere"
;
label define MV505   
    99 "Missing"
;
label define MV510   
     1 "Month and year - information complete"
     2 "Month and age - year imputed"
     3 "Year and age - month imputed"
     5 "Year - age/month imputed"
     6 "Age - year/month imputed"
     7 "Month - age/year imputed"
     8 "None - all imputed"
;
label define MV513   
     0 "Never married"
     1 "0-4"
     2 "5-9"
     3 "10-14"
     4 "15-19"
     5 "20-24"
     6 "25-29"
     7 "30+"
;
label define MV525   
     0 "Not had sex"
    96 "At first union"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV527   
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV528   
    31 "31+ days"
    95 "Within last 4 weeks"
    96 "Before last birth"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV529   
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV531   
     0 "Not had sex"
    97 "Inconsistent"
    98 "Don't know"
;
label define MV532   
     0 "No flag"
     1 "After interview"
     2 "After conception >= 1 year"
     3 "After conception < 1 year"
     4 "At marriage, but never married"
     5 "At marriage, but after conception"
     6 "After marriage"
;
label define MV535   
     0 "No"
     1 "Formerly married"
     2 "Formerly lived with a woman"
     3 "Both, formerly married and lived with a woman"
;
label define MV536   
     0 "Never had sex"
     1 "Active in last 4 weeks"
     3 "Not active in last 4 weeks"
;
label define MV541   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV602   
     1 "Have another"
     2 "Undecided"
     3 "No more"
     4 "Sterilized (respondent or partner(s))"
     5 "Declared infecund (respondent or partner(s))"
     6 "Never had sex"
     7 "Man declared infecund"
     8 "Man has no partner"
;
label define MV603   
   100 "Wanted now"
   101 "Months: 1"
   199 "Months: number missing"
   201 "Years: 1"
   299 "Years: number missing"
   993 "After marriage"
   994 "Soon, now"
   996 "Other, non-numeric"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV604   
     0 "<12 months"
     1 "1 year"
     2 "2 years"
     3 "3 years"
     4 "4 years"
     5 "5 years"
     6 "6+ years"
     7 "Non-numeric"
     8 "Don't know"
;
label define MV605   
     1 "Wants within 2 years"
     2 "Wants after 2+ years"
     3 "Wants, unsure timing"
     4 "Undecided"
     5 "Wants no more"
     6 "Sterilized (respondent or partner(s))"
     7 "Declared infecund (respondent or partner(s))"
     8 "Never had sex"
;
label define MV613   
    96 "Non-numeric response"
    98 "Don't know"
;
label define MV614   
     6 "6+"
     7 "Non-numeric response"
;
label define MV616   
   100 "Wanted now"
   101 "Months: 1"
   199 "Months: number missing"
   201 "Years: 1"
   299 "Years: number missing"
   993 "After marriage"
   994 "Soon/now"
   995 "Can't get pregnant"
   996 "Other"
   998 "Don't know"
;
label define MV621   
     1 "Both want same"
     2 "Wife wants more"
     3 "Wife wants fewer"
     8 "Don't know"
;
label define MV627   
    96 "Other"
    98 "Don't know"
;
label define MV628   
    96 "Other"
    98 "Don't know"
;
label define MV629   
    96 "Other"
    98 "Don't know"
;
label define MV631   
     1 "Big problem"
     2 "Small problem"
     3 "No problem"
     4 "Says she can't get pregnant/not having sex"
;
label define MV633A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV633G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV634A  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634B  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634C  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV634D  
     0 "No"
     1 "Yes"
     8 "Don't know, depends"
;
label define MV714   
     0 "No"
     1 "Yes"
;
label define MV714A  
     0 "No"
     1 "Yes"
;
label define MV716   
     0 "Not working"
    11 "Chief executive, senior officers and legislators"
    12 "Administrative and commercial managers not elsewhere classified"
    13 "Production and specialized service managers"
    14 "Hospitality, retail and other services managers"
    21 "Science and engineering professionals"
    22 "Health professionals"
    23 "Teaching professionals"
    24 "Business and administrative professionals"
    25 "Information and communication technology professionals"
    26 "Legal, social and cultural professional"
    31 "Science and engineering associate professionals"
    32 "Health associate professionals"
    33 "Business and administration associate professionals"
    34 "Legal, social cultural and related associate professionals"
    35 "Information and communications technicians"
    41 "General and keyboard clerks"
    42 "Customer service clerks"
    43 "Numerical and mateial recording clerks"
    44 "Other clerical support workers"
    51 "Personal sales workers"
    52 "Sales workers"
    53 "Personal care workers"
    54 "Protective services workers"
    61 "Market-oriented agricultural workers"
    62 "Market-oriented skilled forestry, fishery and hunting workers"
    63 "Subsistence farmers, fishers, hunters and gatherers"
    71 "Building and related trades workers, excluding electricians"
    72 "Metal, machinery and related trades workers"
    73 "Handicraft and printing workers"
    74 "Electrical and electronic trades workers"
    75 "Food processing, wood working, garment and other craft and related trades workers"
    81 "Stationary plant and machine operators"
    82 "Assemblers"
    83 "Drivers and mobile plant operators"
    91 "Cleaners and helpers"
    92 "Agricultural, forestry and fishery labourers"
    93 "Labours in mining, construction, manufacturing and transport"
    94 "Food preparation assistants"
    95 "Street and related sales and service workers"
    96 "Refuse workers and other elementary workers"
   996 "Other"
;
label define MV717   
     0 "Not working"
     1 "Professional/technical/managerial"
     2 "Clerical"
     3 "Sales"
     4 "Agriculture - self employed"
     5 "Agriculture - employee"
     6 "Household and domestic"
     7 "Services"
     8 "Skilled manual"
     9 "Unskilled manual"
    96 "Other"
    98 "Don't know"
;
label define MV719   
     1 "For family member"
     2 "For someone else"
     3 "Self-employed"
;
label define MV721   
     1 "At home"
     2 "Away"
;
label define MV731   
     0 "No"
     1 "In the past year"
     2 "Currently working"
;
label define MV732   
     1 "All year"
     2 "Seasonal"
     3 "Occasional"
;
label define MV739   
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
;
label define MV740   
     0 "Own land"
     1 "Family land"
     2 "Someone else's land"
     3 "Rented land"
     8 "Don't know"
;
label define MV741   
     0 "Not paid"
     1 "Cash only"
     2 "Cash and in-kind"
     3 "In-kind only"
;
label define MV743A  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Other"
     8 "Don't know/depends"
;
label define MV743B  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Other"
     8 "Don't know/depends"
;
label define MV743C  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743D  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743E  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743F  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV743G  
     1 "Respondent alone"
     2 "Respondent and wife/partner"
     3 "Respondent and other person"
     4 "Wife/partner alone"
     5 "Someone else"
     6 "Decision not made/not applicable"
     8 "Don't know/depends"
;
label define MV744A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV744E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV745A  
     0 "Does not own"
     1 "Alone only"
     2 "Jointly only"
     3 "Both alone and jointly"
;
label define MV745B  
     0 "Does not own"
     1 "Alone only"
     2 "Jointly only"
     3 "Both alone and jointly"
;
label define MV747A  
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV747B  
     0 "Disagree"
     1 "Agree"
     8 "Don't know"
;
label define MV750   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV751   
     0 "No"
     1 "Yes"
;
label define MV754BP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754CP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754DP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754JP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV754WP 
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV756   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV761C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV762AA 
     0 "No"
     1 "Yes"
;
label define MV762AB 
     0 "No"
     1 "Yes"
;
label define MV762AC 
     0 "No"
     1 "Yes"
;
label define MV762AD 
     0 "No"
     1 "Yes"
;
label define MV762AE 
     0 "No"
     1 "Yes"
;
label define MV762AF 
     0 "No"
     1 "Yes"
;
label define MV762AG 
     0 "No"
     1 "Yes"
;
label define MV762AH 
     0 "No"
     1 "Yes"
;
label define MV762AI 
     0 "No"
     1 "Yes"
;
label define MV762AJ 
     0 "No"
     1 "Yes"
;
label define MV762AK 
     0 "No"
     1 "Yes"
;
label define MV762AL 
     0 "No"
     1 "Yes"
;
label define MV762AM 
     0 "No"
     1 "Yes"
;
label define MV762AN 
     0 "No"
     1 "Yes"
;
label define MV762AO 
     0 "No"
     1 "Yes"
;
label define MV762AP 
     0 "No"
     1 "Yes"
;
label define MV762AQ 
     0 "No"
     1 "Yes"
;
label define MV762AR 
     0 "No"
     1 "Yes"
;
label define MV762AS 
     0 "No"
     1 "Yes"
;
label define MV762AT 
     0 "No"
     1 "Yes"
;
label define MV762AU 
     0 "No"
     1 "Yes"
;
label define MV762AV 
     0 "No"
     1 "Yes"
;
label define MV762AW 
     0 "No"
     1 "Yes"
;
label define MV762AX 
     0 "No"
     1 "Yes"
;
label define MV762AZ 
     0 "No"
     1 "Yes: don't know"
;
label define MV762BA 
     0 "No"
     1 "Yes"
;
label define MV762BB 
     0 "No"
     1 "Yes"
;
label define MV762BC 
     0 "No"
     1 "Yes"
;
label define MV762BD 
     0 "No"
     1 "Yes"
;
label define MV762BE 
     0 "No"
     1 "Yes"
;
label define MV762BF 
     0 "No"
     1 "Yes"
;
label define MV762BG 
     0 "No"
     1 "Yes"
;
label define MV762BH 
     0 "No"
     1 "Yes"
;
label define MV762BI 
     0 "No"
     1 "Yes"
;
label define MV762BJ 
     0 "No"
     1 "Yes"
;
label define MV762BK 
     0 "No"
     1 "Yes"
;
label define MV762BL 
     0 "No"
     1 "Yes"
;
label define MV762BM 
     0 "No"
     1 "Yes"
;
label define MV762BN 
     0 "No"
     1 "Yes"
;
label define MV762BO 
     0 "No"
     1 "Yes"
;
label define MV762BP 
     0 "No"
     1 "Yes"
;
label define MV762BQ 
     0 "No"
     1 "Yes"
;
label define MV762BR 
     0 "No"
     1 "Yes"
;
label define MV762BS 
     0 "No"
     1 "Yes"
;
label define MV762BT 
     0 "No"
     1 "Yes"
;
label define MV762BU 
     0 "No"
     1 "Yes"
;
label define MV762BV 
     0 "No"
     1 "Yes"
;
label define MV762BW 
     0 "No"
     1 "Yes"
;
label define MV762BX 
     0 "No"
     1 "Yes"
;
label define MV762BZ 
     0 "No"
     1 "Yes: don't know"
;
label define MV763A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV763G  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV766A  
    98 "Don't know"
;
label define MV766B  
    98 "Don't know"
;
label define MV767A  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV767B  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV767C  
     1 "Spouse"
     2 "Girlfriend/fiance"
     3 "Other friend"
     4 "Casual acquaintance"
     5 "Relative"
     6 "Commercial sex worker"
     7 "Live-in partner"
    96 "Other"
;
label define MV768A  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV768B  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV768C  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Months: 1"
   299 "Months: number missing"
   301 "Years: 1"
   399 "Years: number missing"
;
label define MV769   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV769A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV770   
     0 "No"
     1 "Yes"
;
label define MV770A  
     0 "No"
     1 "Yes"
;
label define MV770B  
     0 "No"
     1 "Yes"
;
label define MV770C  
     0 "No"
     1 "Yes"
;
label define MV770D  
     0 "No"
     1 "Yes"
;
label define MV770E  
     0 "No"
     1 "Yes"
;
label define MV770F  
     0 "No"
     1 "Yes"
;
label define MV770G  
     0 "No"
     1 "Yes"
;
label define MV770H  
     0 "No"
     1 "Yes"
;
label define MV770I  
     0 "No"
     1 "Yes"
;
label define MV770J  
     0 "No"
     1 "Yes"
;
label define MV770K  
     0 "No"
     1 "Yes"
;
label define MV770L  
     0 "No"
     1 "Yes"
;
label define MV770M  
     0 "No"
     1 "Yes"
;
label define MV770N  
     0 "No"
     1 "Yes"
;
label define MV770O  
     0 "No"
     1 "Yes"
;
label define MV770P  
     0 "No"
     1 "Yes"
;
label define MV770Q  
     0 "No"
     1 "Yes"
;
label define MV770R  
     0 "No"
     1 "Yes"
;
label define MV770S  
     0 "No"
     1 "Yes"
;
label define MV770T  
     0 "No"
     1 "Yes"
;
label define MV770U  
     0 "No"
     1 "Yes"
;
label define MV770V  
     0 "No"
     1 "Yes"
;
label define MV770W  
     0 "No"
     1 "Yes"
;
label define MV770X  
     0 "No"
     1 "Yes"
;
label define MV774A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV774B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV774C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV775   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV777   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV778   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV779   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV780   
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV781   
     0 "No"
     1 "Yes"
;
label define MV783   
     0 "No"
     1 "Yes"
;
label define MV784A  
     0 "No"
     1 "Yes"
;
label define MV784B  
     0 "No"
     1 "Yes"
;
label define MV784C  
     0 "No"
     1 "Yes"
;
label define MV784D  
     0 "No"
     1 "Yes"
;
label define MV784E  
     0 "No"
     1 "Yes"
;
label define MV784F  
     0 "No"
     1 "Yes"
;
label define MV784G  
     0 "No"
     1 "Yes"
;
label define MV784H  
     0 "No"
     1 "Yes"
;
label define MV784I  
     0 "No"
     1 "Yes"
;
label define MV784J  
     0 "No"
     1 "Yes"
;
label define MV784K  
     0 "No"
     1 "Yes"
;
label define MV784L  
     0 "No"
     1 "Yes"
;
label define MV784M  
     0 "No"
     1 "Yes"
;
label define MV784N  
     0 "No"
     1 "Yes"
;
label define MV784O  
     0 "No"
     1 "Yes"
;
label define MV784P  
     0 "No"
     1 "Yes"
;
label define MV784Q  
     0 "No"
     1 "Yes"
;
label define MV784R  
     0 "No"
     1 "Yes"
;
label define MV784S  
     0 "No"
     1 "Yes"
;
label define MV784T  
     0 "No"
     1 "Yes"
;
label define MV784U  
     0 "No"
     1 "Yes"
;
label define MV784V  
     0 "No"
     1 "Yes"
;
label define MV784X  
     0 "No"
     1 "Yes"
;
label define MV785   
     0 "No"
     1 "Yes"
;
label define MV791   
     0 "No"
     1 "Yes"
;
label define MV793   
     0 "No"
     1 "Yes"
;
label define MV793A  
     0 "No"
     1 "Yes"
;
label define MV793B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV820   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV822   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV823   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV824   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV825   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV826   
     1 "Less than 12 months"
     2 "12-23 months"
     3 "2 years or more"
;
label define MV826A  
    95 "Two or more years"
    98 "Don't know"
;
label define MV827   
     1 "Asked for the test"
     2 "Offered and accepted"
     3 "Required"
;
label define MV828   
     0 "No"
     1 "Yes"
;
label define MV829   
    11 "Government hospital / polyclinic"
    12 "Government health center"
    13 "Government health post / CHPS"
    14 "Stand-alone VCT center"
    15 "FP clinic"
    16 "Mobile clinic"
    17 "Fieldworker / outreach / peer educator"
    18 "Other public"
    21 "Private hospital/clinic/private doctor"
    22 "Stand-alone VCT Center"
    23 "Pharmacy"
    24 "Chemical / drug store"
    25 "FP / PPAG Clinic"
    26 "Maternity home"
    27 "Other private medical"
    31 "Home"
    32 "Correctional facility"
    96 "Other"
;
label define MV832B  
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV832C  
   100 "<1 day ago"
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   995 "Within last 4 weeks"
   996 "Before last birth"
   997 "Inconsistent"
   998 "Don't know"
;
label define MV833A  
     0 "No"
     1 "Yes"
;
label define MV833B  
     0 "No"
     1 "Yes"
;
label define MV833C  
     0 "No"
     1 "Yes"
;
label define MV834A  
    95 "95+"
    98 "Don't know"
;
label define MV834B  
    95 "95+"
    98 "Don't know"
;
label define MV834C  
    95 "95+"
    98 "Don't know"
;
label define MV835A  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV835B  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV835C  
     0 "No"
     1 "Respondent drunk only"
     2 "Partner drunk only"
     3 "Both drunk"
     4 "Neither drunk but consumed alcohol"
;
label define MV836   
    95 "95+"
    98 "Don't know"
;
label define MV837   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define MV844   
     0 "No"
     1 "Yes"
     8 "Don't know anyone with AIDS"
;
label define MV845   
     0 "No"
     1 "Yes"
;
label define MV846   
     0 "No"
     1 "Yes"
;
label define MV847   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/no opinion"
;
label define MV848   
     0 "Disagree"
     1 "Agree"
     8 "Don't know/no opinion"
;
label define MV849   
     0 "No"
     1 "Yes"
     8 "Don't know/depends"
;
label define MV851A  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851B  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851C  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851D  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851E  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851F  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851G  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851H  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851I  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851J  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851K  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV851L  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure/depends"
;
label define MV852A  
   100 "Today"
   101 "Days 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV852B  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV852C  
   101 "Days: 1"
   199 "Days: number missing"
   201 "Weeks: 1"
   299 "Weeks: number missing"
   301 "Months: 1"
   399 "Months: number missing"
   401 "Years: 1"
   499 "Years: number missing"
;
label define MV853A  
    95 "95+"
    98 "Don't know"
;
label define MV853B  
    95 "95+"
    98 "Don't know"
;
label define MV853C  
    95 "95+"
    98 "Don't know"
;
label define MV854A  
     0 "No"
     1 "Yes"
;
label define MV854B  
     0 "No"
     1 "Yes"
;
label define SMLANQ  
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
     5 "Nzema"
     6 "Dagbani"
     7 "Other"
;
label define SMLANI  
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
     5 "Nzema"
     6 "Dagbani"
    96 "Other"
;
label define SMLANR  
     1 "English"
     2 "Akan"
     3 "Ga"
     4 "Ewe"
     5 "Nzema"
     6 "Dagbani"
    96 "Other"
;
label define SMTRANS 
     0 "No"
     1 "Yes"
;
label define SM101A  
     1 "Respondent agrees"
     2 "Respondent disagrees"
;
label define SM101B1 
     0 "No"
     1 "Yes"
;
label define SM101B2 
     0 "No"
     1 "Yes"
;
label define SM101B3 
     0 "No"
     1 "Yes"
;
label define SM101B4 
     0 "No"
     1 "Yes"
;
label define SM101C  
    95 "95+"
;
label define SM101D  
     1 "Model 767, Small: 16 CM - 23 CM"
     2 "Model 767, Medium: 24 CM - 35 CM"
     3 "Model767, Large: 36 CM - 41 CM"
     4 "Model 789, Large: 42 CM - 60 CM"
;
label define SM101E1 
     0 "Special answer expected"
;
label define SM101E2 
   999 "Missing"
;
label define SM101E3 
   994 "Refused"
   995 "Technical problems"
   996 "Other"
;
label define SM105   
     1 "Primary"
     2 "Middle"
     3 "JSS/JHS"
     4 "Secondary"
     5 "SSS/SHS"
     6 "Higher"
;
label define SM106   
    99 "Missing"
;
label define SMEDUC  
     0 "No education"
     1 "Primary"
     2 "Middle/JHS/JSS"
     3 "Secondary/SSS/SHS/Higher"
;
label define SM106B  
    99 "Missing"
;
label define SM106C  
     0 "No"
     1 "Yes"
;
label define SM106D  
     1 "Had to work"
     2 "Moved"
     3 "No money to cover costs"
     4 "Had bad grades"
     5 "Health reasons"
     6 "Got married / family reasons"
     7 "Completed desired level"
     8 "No desire to continue"
     9 "Waiting for admission"
    96 "Other"
;
label define SM401A  
     0 "No"
     1 "Yes"
;
label define SM401B1 
     0 "No"
     1 "Yes"
;
label define SM401B2 
     0 "No"
     1 "Yes"
;
label define SM401B3 
     0 "No"
     1 "Yes"
;
label define SM401B4 
     0 "No"
     1 "Yes"
;
label define SM401B5 
     0 "No"
     1 "Yes"
;
label define SM401B6 
     0 "No"
     1 "Yes"
;
label define SM401B7 
     0 "No"
     1 "Yes"
;
label define SM401B8 
     0 "No"
     1 "Yes"
;
label define SM401B9 
     0 "No"
     1 "Yes"
;
label define SM401C  
     1 "Paid in full"
     2 "Partly paid"
     3 "Not paid at all"
     6 "Other"
;
label define SM401D1 
     0 "No"
     1 "Yes"
;
label define SM401D2 
     0 "No"
     1 "Yes"
;
label define SM401D3 
     0 "No"
     1 "Yes"
;
label define SM401D4 
     0 "No"
     1 "Yes"
;
label define SM401D5 
     0 "No"
     1 "Yes"
;
label define SM401D6 
     0 "No"
     1 "Yes"
;
label define SM401D7 
     0 "No"
     1 "Yes"
;
label define SM401D8 
     0 "No"
     1 "Yes"
;
label define SM401D9 
     0 "No"
     1 "Yes"
;
label define SM500B  
     1 "Respondent agrees"
     2 "Respondent disagrees"
;
label define SM500C1 
     0 "Special answer"
;
label define SM500C2 
   999 "Missing"
;
label define SM500C3 
   994 "Refused"
   995 "Technical problems"
   996 "Other"
;
label define SM710A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM812A  
     0 "No"
     1 "Yes"
;
label define SM814A  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM814B  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM814C  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM814D  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM814E  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM814F  
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM816A  
     0 "No"
     1 "Yes"
;
label define SM816B  
     0 "No"
     1 "Yes"
;
label define SM816C  
     0 "No"
     1 "Yes"
;
label define SM816D  
     0 "No"
     1 "Yes"
;
label define SM816E  
     0 "No"
     1 "Yes"
;
label define SM816F  
     0 "No"
     1 "Yes"
;
label define SM816G  
     0 "No"
     1 "Yes"
;
label define SM816H  
     0 "No"
     1 "Yes"
;
label define SM816I  
     0 "No"
     1 "Yes"
;
label define SM816J  
     0 "No"
     1 "Yes"
;
label define SM816X  
     0 "No"
     1 "Yes"
;
label define SM817   
     1 "Yes, paid myself"
     2 "Yes, paid by a relative / friend"
     3 "Yes, paid by employer/ssnit"
     4 "No, exempt as elderly"
     5 "No, exempt as pensioner"
     7 "No, exempt as indigent"
     6 "No, other"
;
label define SM818   
     0 "No"
     1 "Yes, card seen"
     2 "Yes, card not seen"
;
label define SM819   
     1 "Registered, not paid fully"
     2 "Registered, card not received"
     3 "Registered, waiting period"
     4 "Not renewed registration"
     5 "Lost NHIS card"
     6 "Other"
;
label define SM820   
    95 "95+ weeks"
    98 "Don't know"
;
label define SM821   
     0 "No"
     1 "Yes"
     8 "Don't know / not sure"
;
label define SM822A  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure"
;
label define SM822B  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure"
;
label define SM822C  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure"
;
label define SM822D  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure"
;
label define SM822E  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure"
;
label define SM822F  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure"
;
label define SM822G  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure"
;
label define SM822H  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure"
;
label define SM822X  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure"
;
label define SM823   
     0 "No"
     1 "Yes"
     8 "Don't know / not sure"
;
label define SM824   
     0 "No"
     1 "Yes"
     8 "Don't know / not sure"
;
label define SM825A  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure"
;
label define SM825B  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure"
;
label define SM825C  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure"
;
label define SM825D  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure"
;
label define SM825E  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure"
;
label define SM825X  
     0 "No"
     1 "Yes"
     8 "Don't know/not sure"
;
label define SM826   
     1 "Better"
     2 "Same"
     3 "Worse"
     8 "Don't know / not sure"
;
label define SM827   
     1 "Yes"
     2 "No, waiting times too long"
     3 "No, staff not polite"
     4 "No, did not receive enough information about illness and treatment"
     6 "Other"
;
label define SM828   
     0 "No"
     1 "Yes"
;
label define SM829A  
     0 "No"
     1 "Yes"
;
label define SM829X  
     0 "No"
     1 "Yes"
;
label define SM830   
     0 "No"
     1 "Yes"
;
label define SM831A  
     0 "No"
     1 "Yes"
;
label define SM831X  
     0 "No"
     1 "Yes"
;
label define SM836   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM837   
     0 "No"
     1 "Yes"
     8 "Don't know"
;
label define SM838A  
     0 "No"
     1 "Yes"
     3 "N/A"
;
label define SM838B  
     0 "No"
     1 "Yes"
     3 "N/A"
;
label define SM838C  
     0 "No"
     1 "Yes"
     3 "N/A"
;
label define SM838D  
     0 "No"
     1 "Yes"
     3 "N/A"
;
label define SM838E  
     0 "No"
     1 "Yes"
     3 "N/A"
;
label define SM838F  
     0 "No"
     1 "Yes"
     3 "N/A"
;
label define SM839   
     0 "No"
     1 "Yes"
;
label define SM840A  
     0 "No"
     1 "Yes"
;
label define SM840B  
     0 "No"
     1 "Yes"
;
label define SM840C  
     0 "No"
     1 "Yes"
;
label define SM840D  
     0 "No"
     1 "Yes"
;
label define SM840E  
     0 "No"
     1 "Yes"
;
label define SM840F  
     0 "No"
     1 "Yes"
;
label define SM840X  
     0 "No"
     1 "Yes"
;
label define SM840Z  
     0 "No"
     1 "Yes"
;
label define SM841A  
     0 "No"
     1 "Yes"
;
label define SM841B  
     0 "No"
     1 "Yes"
;
label define SM841C  
     0 "No"
     1 "Yes"
;
label define SM841X  
     0 "No"
     1 "Yes"
;
label define SM841Z  
     0 "No"
     1 "Yes"
;
label define SM842   
     0 "None"
     8 "Don't know / not sure"
;
label define SM844   
     0 "None"
     8 "Don't know / not sure"
;
label define SM846   
     0 "No"
     1 "Yes"
;
label define SM847   
     1 "Public / government"
     2 "Private"
     6 "Other"
     8 "Don't know"
;
label define SM848   
     1 "Family planning"
     2 "ANC/Delivery/PNC"
     3 "Newborn care"
     4 "Malaria"
     5 "Fever"
     6 "Diarrhoea"
     7 "HIV/AIDS/STI"
     8 "High blood pressure"
     9 "Ear/nose/throat/ infection"
    10 "Diabetes"
    11 "Eye infection"
    12 "Checkup/preventive care"
    13 "Accident/injury"
    14 "Other outpatient service"
    15 "Pregnancy/delivery"
    16 "Child illness"
    17 "Her own illness"
    18 "Accident/injury"
    19 "Other inpatient service"
    96 "Other"
;
label define SM849   
     1 "Cash"
     2 "National health insurance"
     3 "Other insurance"
     4 "Combination of any of the above"
     6 "Other"
;
label define SM850   
     1 "Very easy"
     2 "Easy"
     3 "Fairly easy"
     4 "Difficult"
     5 "Very difficult"
;
label define SM851   
     1 "Very convenient"
     2 "Convenient"
     3 "Fairly convenient"
     4 "Not convenient"
     5 "Very convenient"
;
label define SM852   
     1 "Very good"
     2 "Good"
     3 "Fair"
     4 "Poor"
     5 "Very poor"
;
label define SM853A  
     1 "Very satisfied"
     2 "Satisfied"
     3 "Fairly satisfied"
     4 "Not satisfied"
     5 "Very dissatisfied"
     6 "Not applicable"
;
label define SM853B  
     1 "Very satisfied"
     2 "Satisfied"
     3 "Fairly satisfied"
     4 "Not satisfied"
     5 "Very dissatisfied"
     6 "Not applicable"
;
label define SM853C  
     1 "Very satisfied"
     2 "Satisfied"
     3 "Fairly satisfied"
     4 "Not satisfied"
     5 "Very dissatisfied"
     6 "Not applicable"
;
label define SM853D  
     1 "Very satisfied"
     2 "Satisfied"
     3 "Fairly satisfied"
     4 "Not satisfied"
     5 "Very dissatisfied"
     6 "Not applicable"
;
label define SM853E  
     1 "Very satisfied"
     2 "Satisfied"
     3 "Fairly satisfied"
     4 "Not satisfied"
     5 "Very dissatisfied"
     6 "Not applicable"
;
label define SM854A  
     1 "Very satisfied"
     2 "Satisfied"
     3 "Fairly satisfied"
     4 "Not satisfied"
     5 "Very dissatisfied"
;
label define SM854B  
     1 "Very satisfied"
     2 "Satisfied"
     3 "Fairly satisfied"
     4 "Not satisfied"
     5 "Very dissatisfied"
;
label define SM854C  
     1 "Very satisfied"
     2 "Satisfied"
     3 "Fairly satisfied"
     4 "Not satisfied"
     5 "Very dissatisfied"
;
label define SM855   
     0 "No"
     1 "Yes"
;
label define SM856   
     0 "No"
     1 "Yes"
;
label define SM857   
     0 "No"
     1 "Yes"
;
label define SM858A  
     1 "Very satisfied"
     2 "Satisfied"
     3 "Fairly satisfied"
     4 "Not satisfied"
     5 "Very dissatisfied"
;
label define SM858B  
     1 "Very satisfied"
     2 "Satisfied"
     3 "Fairly satisfied"
     4 "Not satisfied"
     5 "Very dissatisfied"
;
label define SM858C  
     1 "Very satisfied"
     2 "Satisfied"
     3 "Fairly satisfied"
     4 "Not satisfied"
     5 "Very dissatisfied"
;
label define SM858D  
     1 "Very satisfied"
     2 "Satisfied"
     3 "Fairly satisfied"
     4 "Not satisfied"
     5 "Very dissatisfied"
;
label define SM858E  
     1 "Very satisfied"
     2 "Satisfied"
     3 "Fairly satisfied"
     4 "Not satisfied"
     5 "Very dissatisfied"
;
label define SM861   
     1 "Respondent agrees"
     2 "Respondent disagrees"
;
label define SM862A  
     0 "Special answer"
;
label define SM862B  
   999 "Missing"
;
label define SM862C  
   994 "Refused"
   995 "Technical problems"
   996 "Other"
;

#delimit cr
label values mv013    MV013   
label values mv014    MV014   
label values mv015    MV015   
label values mv022    MV022   
label values mv023    MV023   
label values mv024    MV024   
label values mv025    MV025   
label values mv026    MV026   
label values mv034_1  MV034   
label values mv034_2  MV034   
label values mv034_3  MV034   
label values mv034_4  MV034   
label values mv034_5  MV034   
label values mv034_6  MV034   
label values mv034_7  MV034   
label values mv034_8  MV034   
label values mv034a_1 MV034A  
label values mv034a_2 MV034A  
label values mv034a_3 MV034A  
label values mv034a_4 MV034A  
label values mv034a_5 MV034A  
label values mv034a_6 MV034A  
label values mv034a_7 MV034A  
label values mv034a_8 MV034A  
label values mv035    MV035   
label values mv803    MV803   
label values mv101    MV101   
label values mv102    MV102   
label values mv103    MV103   
label values mv104    MV104   
label values mv105    MV105   
label values mv106    MV106   
label values mv107    MV107   
label values mv130    MV130   
label values mv131    MV131   
label values mv133    MV133   
label values mv134    MV134   
label values mv135    MV135   
label values mv149    MV149   
label values mv150    MV150   
label values mv151    MV151   
label values mv152    MV152   
label values mv155    MV155   
label values mv156    MV156   
label values mv157    MV157   
label values mv158    MV158   
label values mv159    MV159   
label values mv167    MV167   
label values mv168    MV168   
label values mv190    MV190   
label values mv213    MV213   
label values mv217    MV217   
label values mv225    MV225   
label values mv246    MV246   
label values mv248    MV248   
label values mv249    MV249   
label values mv250    MV250   
label values mv251    MV251   
label values mv252    MV252   
label values mv301    MV301   
label values mv302    MV302   
label values m304a_01 M304A   
label values m304a_02 M304A   
label values m304a_03 M304A   
label values m304a_04 M304A   
label values m304a_05 M304A   
label values m304a_06 M304A   
label values m304a_07 M304A   
label values m304a_08 M304A   
label values m304a_09 M304A   
label values m304a_10 M304A   
label values m304a_11 M304A   
label values m304a_12 M304A   
label values m304a_13 M304A   
label values m304a_14 M304A   
label values m304a_15 M304A   
label values m304a_16 M304A   
label values m304a_17 M304A   
label values m304a_18 M304A   
label values m304a_19 M304A   
label values m304a_20 M304A   
label values mv304_01 MV304   
label values mv304_02 MV304   
label values mv304_03 MV304   
label values mv304_04 MV304   
label values mv304_05 MV304   
label values mv304_06 MV304   
label values mv304_07 MV304   
label values mv304_08 MV304   
label values mv304_09 MV304   
label values mv304_10 MV304   
label values mv304_11 MV304   
label values mv304_12 MV304   
label values mv304_13 MV304   
label values mv304_14 MV304   
label values mv304_15 MV304   
label values mv304_16 MV304   
label values mv304_17 MV304   
label values mv304_18 MV304   
label values mv304_19 MV304   
label values mv304_20 MV304   
label values mv305_01 MV305   
label values mv305_02 MV305   
label values mv305_03 MV305   
label values mv305_04 MV305   
label values mv305_05 MV305   
label values mv305_06 MV305   
label values mv305_07 MV305   
label values mv305_08 MV305   
label values mv305_09 MV305   
label values mv305_10 MV305   
label values mv305_11 MV305   
label values mv305_12 MV305   
label values mv305_13 MV305   
label values mv305_14 MV305   
label values mv305_15 MV305   
label values mv305_16 MV305   
label values mv305_17 MV305   
label values mv305_18 MV305   
label values mv305_19 MV305   
label values mv305_20 MV305   
label values mv307_01 MV307   
label values mv307_02 MV307   
label values mv307_03 MV307   
label values mv307_04 MV307   
label values mv307_05 MV307   
label values mv307_06 MV307   
label values mv307_07 MV307   
label values mv307_08 MV307   
label values mv307_09 MV307   
label values mv307_10 MV307   
label values mv307_11 MV307   
label values mv307_12 MV307   
label values mv307_13 MV307   
label values mv307_14 MV307   
label values mv307_15 MV307   
label values mv307_16 MV307   
label values mv307_17 MV307   
label values mv307_18 MV307   
label values mv307_19 MV307   
label values mv307_20 MV307   
label values mv312    MV312   
label values mv313    MV313   
label values mv323a   MV323A  
label values mv325b   MV325B  
label values mv372a   MV372A  
label values mv384a   MV384A  
label values mv384b   MV384B  
label values mv384c   MV384C  
label values mv395    MV395   
label values mv396    MV396   
label values mv3a09b  MV3A09B 
label values mv3b17   MV3B17  
label values mv3b25a  MV3B25A 
label values mv3b25b  MV3B25B 
label values mv463a   MV463A  
label values mv463b   MV463B  
label values mv463c   MV463C  
label values mv463d   MV463D  
label values mv463e   MV463E  
label values mv463f   MV463F  
label values mv463g   MV463G  
label values mv463x   MV463X  
label values mv463z   MV463Z  
label values mv464    MV464   
label values mv474    MV474   
label values mv474a   MV474A  
label values mv474b   MV474B  
label values mv474c   MV474C  
label values mv474d   MV474D  
label values mv474e   MV474E  
label values mv474f   MV474F  
label values mv474g   MV474G  
label values mv474h   MV474H  
label values mv474i   MV474I  
label values mv474j   MV474J  
label values mv474x   MV474X  
label values mv474z   MV474Z  
label values mv475    MV475   
label values mv476    MV476   
label values mv477    MV477   
label values mv478    MV478   
label values mv479    MV479   
label values mv480    MV480   
label values mv481    MV481   
label values mv481a   MV481A  
label values mv481b   MV481B  
label values mv481c   MV481C  
label values mv481d   MV481D  
label values mv481e   MV481E  
label values mv481f   MV481F  
label values mv481g   MV481G  
label values mv481h   MV481H  
label values mv481x   MV481X  
label values mv482a   MV482A  
label values mv482b   MV482B  
label values mv482c   MV482C  
label values mv483    MV483   
label values mv483a   MV483A  
label values mv483b   MV483B  
label values mv483c   MV483C  
label values mv501    MV501   
label values mv502    MV502   
label values mv503    MV503   
label values mv504    MV504   
label values mv510    MV510   
label values mv513    MV513   
label values mv525    MV525   
label values mv527    MV527   
label values mv528    MV528   
label values mv529    MV529   
label values mv531    MV531   
label values mv532    MV532   
label values mv535    MV535   
label values mv536    MV536   
label values mv541    MV541   
label values mv602    MV602   
label values mv603    MV603   
label values mv604    MV604   
label values mv605    MV605   
label values mv613    MV613   
label values mv614    MV614   
label values mv616    MV616   
label values mv621    MV621   
label values mv627    MV627   
label values mv628    MV628   
label values mv629    MV629   
label values mv631    MV631   
label values mv633a   MV633A  
label values mv633b   MV633B  
label values mv633c   MV633C  
label values mv633d   MV633D  
label values mv633e   MV633E  
label values mv633f   MV633F  
label values mv633g   MV633G  
label values mv634a   MV634A  
label values mv634b   MV634B  
label values mv634c   MV634C  
label values mv634d   MV634D  
label values mv714    MV714   
label values mv714a   MV714A  
label values mv716    MV716   
label values mv717    MV717   
label values mv719    MV719   
label values mv721    MV721   
label values mv731    MV731   
label values mv732    MV732   
label values mv739    MV739   
label values mv740    MV740   
label values mv741    MV741   
label values mv743a   MV743A  
label values mv743b   MV743B  
label values mv743c   MV743C  
label values mv743d   MV743D  
label values mv743e   MV743E  
label values mv743f   MV743F  
label values mv743g   MV743G  
label values mv744a   MV744A  
label values mv744b   MV744B  
label values mv744c   MV744C  
label values mv744d   MV744D  
label values mv744e   MV744E  
label values mv745a   MV745A  
label values mv745b   MV745B  
label values mv747a   MV747A  
label values mv747b   MV747B  
label values mv750    MV750   
label values mv751    MV751   
label values mv754bp  MV754BP 
label values mv754cp  MV754CP 
label values mv754dp  MV754DP 
label values mv754jp  MV754JP 
label values mv754wp  MV754WP 
label values mv756    MV756   
label values mv761    MV761   
label values mv761b   MV761B  
label values mv761c   MV761C  
label values mv762aa  MV762AA 
label values mv762ab  MV762AB 
label values mv762ac  MV762AC 
label values mv762ad  MV762AD 
label values mv762ae  MV762AE 
label values mv762af  MV762AF 
label values mv762ag  MV762AG 
label values mv762ah  MV762AH 
label values mv762ai  MV762AI 
label values mv762aj  MV762AJ 
label values mv762ak  MV762AK 
label values mv762al  MV762AL 
label values mv762am  MV762AM 
label values mv762an  MV762AN 
label values mv762ao  MV762AO 
label values mv762ap  MV762AP 
label values mv762aq  MV762AQ 
label values mv762ar  MV762AR 
label values mv762as  MV762AS 
label values mv762at  MV762AT 
label values mv762au  MV762AU 
label values mv762av  MV762AV 
label values mv762aw  MV762AW 
label values mv762ax  MV762AX 
label values mv762az  MV762AZ 
label values mv762ba  MV762BA 
label values mv762bb  MV762BB 
label values mv762bc  MV762BC 
label values mv762bd  MV762BD 
label values mv762be  MV762BE 
label values mv762bf  MV762BF 
label values mv762bg  MV762BG 
label values mv762bh  MV762BH 
label values mv762bi  MV762BI 
label values mv762bj  MV762BJ 
label values mv762bk  MV762BK 
label values mv762bl  MV762BL 
label values mv762bm  MV762BM 
label values mv762bn  MV762BN 
label values mv762bo  MV762BO 
label values mv762bp  MV762BP 
label values mv762bq  MV762BQ 
label values mv762br  MV762BR 
label values mv762bs  MV762BS 
label values mv762bt  MV762BT 
label values mv762bu  MV762BU 
label values mv762bv  MV762BV 
label values mv762bw  MV762BW 
label values mv762bx  MV762BX 
label values mv762bz  MV762BZ 
label values mv763a   MV763A  
label values mv763b   MV763B  
label values mv763c   MV763C  
label values mv763d   MV763D  
label values mv763e   MV763E  
label values mv763f   MV763F  
label values mv763g   MV763G  
label values mv766a   MV766A  
label values mv766b   MV766B  
label values mv767a   MV767A  
label values mv767b   MV767B  
label values mv767c   MV767C  
label values mv768a   MV768A  
label values mv768b   MV768B  
label values mv768c   MV768C  
label values mv769    MV769   
label values mv769a   MV769A  
label values mv770    MV770   
label values mv770a   MV770A  
label values mv770b   MV770B  
label values mv770c   MV770C  
label values mv770d   MV770D  
label values mv770e   MV770E  
label values mv770f   MV770F  
label values mv770g   MV770G  
label values mv770h   MV770H  
label values mv770i   MV770I  
label values mv770j   MV770J  
label values mv770k   MV770K  
label values mv770l   MV770L  
label values mv770m   MV770M  
label values mv770n   MV770N  
label values mv770o   MV770O  
label values mv770p   MV770P  
label values mv770q   MV770Q  
label values mv770r   MV770R  
label values mv770s   MV770S  
label values mv770t   MV770T  
label values mv770u   MV770U  
label values mv770v   MV770V  
label values mv770w   MV770W  
label values mv770x   MV770X  
label values mv774a   MV774A  
label values mv774b   MV774B  
label values mv774c   MV774C  
label values mv775    MV775   
label values mv777    MV777   
label values mv778    MV778   
label values mv779    MV779   
label values mv780    MV780   
label values mv781    MV781   
label values mv783    MV783   
label values mv784a   MV784A  
label values mv784b   MV784B  
label values mv784c   MV784C  
label values mv784d   MV784D  
label values mv784e   MV784E  
label values mv784f   MV784F  
label values mv784g   MV784G  
label values mv784h   MV784H  
label values mv784i   MV784I  
label values mv784j   MV784J  
label values mv784k   MV784K  
label values mv784l   MV784L  
label values mv784m   MV784M  
label values mv784n   MV784N  
label values mv784o   MV784O  
label values mv784p   MV784P  
label values mv784q   MV784Q  
label values mv784r   MV784R  
label values mv784s   MV784S  
label values mv784t   MV784T  
label values mv784u   MV784U  
label values mv784v   MV784V  
label values mv784x   MV784X  
label values mv785    MV785   
label values mv791    MV791   
label values mv793    MV793   
label values mv793a   MV793A  
label values mv793b   MV793B  
label values mv820    MV820   
label values mv822    MV822   
label values mv823    MV823   
label values mv824    MV824   
label values mv825    MV825   
label values mv826    MV826   
label values mv826a   MV826A  
label values mv827    MV827   
label values mv828    MV828   
label values mv829    MV829   
label values mv832b   MV832B  
label values mv832c   MV832C  
label values mv833a   MV833A  
label values mv833b   MV833B  
label values mv833c   MV833C  
label values mv834a   MV834A  
label values mv834b   MV834B  
label values mv834c   MV834C  
label values mv835a   MV835A  
label values mv835b   MV835B  
label values mv835c   MV835C  
label values mv836    MV836   
label values mv837    MV837   
label values mv844    MV844   
label values mv845    MV845   
label values mv846    MV846   
label values mv847    MV847   
label values mv848    MV848   
label values mv849    MV849   
label values mv851a   MV851A  
label values mv851b   MV851B  
label values mv851c   MV851C  
label values mv851d   MV851D  
label values mv851e   MV851E  
label values mv851f   MV851F  
label values mv851g   MV851G  
label values mv851h   MV851H  
label values mv851i   MV851I  
label values mv851j   MV851J  
label values mv851k   MV851K  
label values mv851l   MV851L  
label values mv852a   MV852A  
label values mv852b   MV852B  
label values mv852c   MV852C  
label values mv853a   MV853A  
label values mv853b   MV853B  
label values mv853c   MV853C  
label values mv854a   MV854A  
label values mv854b   MV854B  
label values smlanq   SMLANQ  
label values smlani   SMLANI  
label values smlanr   SMLANR  
label values smtrans  SMTRANS 
label values sm101a   SM101A  
label values sm101b1  SM101B1 
label values sm101b2  SM101B2 
label values sm101b3  SM101B3 
label values sm101b4  SM101B4 
label values sm101c   SM101C  
label values sm101d   SM101D  
label values sm101e1  SM101E1 
label values sm101e3  SM101E3 
label values sm105    SM105   
label values smeduc   SMEDUC  
label values sm106c   SM106C  
label values sm106d   SM106D  
label values sm401a   SM401A  
label values sm401b1  SM401B1 
label values sm401b2  SM401B2 
label values sm401b3  SM401B3 
label values sm401b4  SM401B4 
label values sm401b5  SM401B5 
label values sm401b6  SM401B6 
label values sm401b7  SM401B7 
label values sm401b8  SM401B8 
label values sm401b9  SM401B9 
label values sm401c   SM401C  
label values sm401d1  SM401D1 
label values sm401d2  SM401D2 
label values sm401d3  SM401D3 
label values sm401d4  SM401D4 
label values sm401d5  SM401D5 
label values sm401d6  SM401D6 
label values sm401d7  SM401D7 
label values sm401d8  SM401D8 
label values sm401d9  SM401D9 
label values sm500b   SM500B  
label values sm500c1  SM500C1 
label values sm500c3  SM500C3 
label values sm710a   SM710A  
label values sm812a   SM812A  
label values sm814a   SM814A  
label values sm814b   SM814B  
label values sm814c   SM814C  
label values sm814d   SM814D  
label values sm814e   SM814E  
label values sm814f   SM814F  
label values sm816a   SM816A  
label values sm816b   SM816B  
label values sm816c   SM816C  
label values sm816d   SM816D  
label values sm816e   SM816E  
label values sm816f   SM816F  
label values sm816g   SM816G  
label values sm816h   SM816H  
label values sm816i   SM816I  
label values sm816j   SM816J  
label values sm816x   SM816X  
label values sm817    SM817   
label values sm818    SM818   
label values sm819    SM819   
label values sm820    SM820   
label values sm821    SM821   
label values sm822a   SM822A  
label values sm822b   SM822B  
label values sm822c   SM822C  
label values sm822d   SM822D  
label values sm822e   SM822E  
label values sm822f   SM822F  
label values sm822g   SM822G  
label values sm822h   SM822H  
label values sm822x   SM822X  
label values sm823    SM823   
label values sm824    SM824   
label values sm825a   SM825A  
label values sm825b   SM825B  
label values sm825c   SM825C  
label values sm825d   SM825D  
label values sm825e   SM825E  
label values sm825x   SM825X  
label values sm826    SM826   
label values sm827    SM827   
label values sm828    SM828   
label values sm829a   SM829A  
label values sm829x   SM829X  
label values sm830    SM830   
label values sm831a   SM831A  
label values sm831x   SM831X  
label values sm836    SM836   
label values sm837    SM837   
label values sm838a   SM838A  
label values sm838b   SM838B  
label values sm838c   SM838C  
label values sm838d   SM838D  
label values sm838e   SM838E  
label values sm838f   SM838F  
label values sm839    SM839   
label values sm840a   SM840A  
label values sm840b   SM840B  
label values sm840c   SM840C  
label values sm840d   SM840D  
label values sm840e   SM840E  
label values sm840f   SM840F  
label values sm840x   SM840X  
label values sm840z   SM840Z  
label values sm841a   SM841A  
label values sm841b   SM841B  
label values sm841c   SM841C  
label values sm841x   SM841X  
label values sm841z   SM841Z  
label values sm842    SM842   
label values sm844    SM844   
label values sm846    SM846   
label values sm847    SM847   
label values sm848    SM848   
label values sm849    SM849   
label values sm850    SM850   
label values sm851    SM851   
label values sm852    SM852   
label values sm853a   SM853A  
label values sm853b   SM853B  
label values sm853c   SM853C  
label values sm853d   SM853D  
label values sm853e   SM853E  
label values sm854a   SM854A  
label values sm854b   SM854B  
label values sm854c   SM854C  
label values sm855    SM855   
label values sm856    SM856   
label values sm857    SM857   
label values sm858a   SM858A  
label values sm858b   SM858B  
label values sm858c   SM858C  
label values sm858d   SM858D  
label values sm858e   SM858E  
label values sm861    SM861   
label values sm862a   SM862A  
label values sm862c   SM862C  
